In [1]:
#Thecnical and summary 
#RILOOING AVERAGE 90, 30, 15,5
#STANDARDEVIATION 90, 30, 15,5
#CHANGE IN ELVES, LAST DAY,
#CHANGE LEVEL LAST 5DA YS, 
#CAHNGE LAST MONT , CHNGE LAST 3MONTHS
#ZSCORE
#HIGH, 
#LOW

#REGIONAL 
#forst version all time series
#secodn verison only since 2017

#PLOT, NORMAL,
#PLOT NROMAL,
#PLOT DIFFERNECE
#PLOTZSCORES
#PPLT#BASE YEAR 2010
#COMPRAE CORSS PLOT HIGHEST CHANGES
#PLOT CROSS HIGES ZSCOERRE

#corss latest
#corss average 5 da
#cross average 30d
#cross zscore90
#cross zscore180
#cross zscore360
#cross differnece 5
#cross differnece 30
#tail nad tables

#https://stackoverflow.com/questions/44751045/save-pandas-table-filled-with-strings-as-png
#https://note.nkmk.me/en/python-os-getcwd-chdir/
#https://stackoverflow.com/questions/50853632/saving-file-object-using-matplotlib-savefig-creating-tar-file-from-multiple-svg
#https://ourcodingclub.github.io/tutorials/pandas-time-series/
#https://www.machinelearningplus.com/plots/top-50-matplotlib-visualizations-the-master-plots-python/#35.-Time-Series-Plot

In [2]:
#import pacakages
import pandas as pd
import numpy as np

from datetime import datetime
from datetime import timedelta
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import statsmodels.api as sm

#improt packages
import datetime as dt
from datetime import datetime
import matplotlib
matplotlib.use('Agg')
import pandas as pd
from pandas import DataFrame
from statsmodels.regression.rolling import RollingOLS
import matplotlib.pyplot as plt
import numpy as np # numerical python
import pandas as pd # pannel datasets
import matplotlib.pyplot as plt 
import seaborn as sns
from datetime import date

#stacked
#import tkinter
#import matplotlib
#import matplotlib.pyplot as plt
#matplotlib.use('TkAgg')
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import warnings; warnings.filterwarnings(action='once')

# importing os module
import os


from pandas import DataFrame
import matplotlib.pyplot as plt
from datetime import date
import seaborn as sns
from datetime import datetime


import numpy as np
import PIL
from PIL import Image

import pandas as pd
import matplotlib.pylab as plt
from pandas.plotting import table
from pandas.plotting import table
from pandas.plotting import table

from pandas.plotting import table

#this from pandas.plotting import table
#import matplotlib.pyplot as plt

#import pandas as pd
#import matplotlib.pylab as plt
#from pandas.plotting import table


from codetiming import Timer
timeclock = Timer(name="class")
timeclock.start()
# Do something

In [3]:
#Define fuycnitons

def plot_series(series):
    plt.figure(figsize=(6,3))
    plt.plot(series, color = 'red')
    plt.ylabel(series.name, fontsize = 16)
    plt.show()
    
    
def zscore(x, window):
    r = x.rolling(window=window)
    m = r.mean().shift(1)
    s = r.std(ddof=0).shift(1)
    z = (x-m)/s
    return z


def zscore_using_apply(x, window):
    def zscore_func(x):
        return (x[-1] - x[:-1].mean())/x[:-1].std(ddof=0)
    return x.rolling(window=window+1).apply(zscore_func)

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [4]:
#sTEP1 READ THHE INPUT TABLE AND RENAME ALL COLUMNS, TRNASOMFR DATA
#read talbe
cds_tmp = pd.read_csv (r'K:\2020_2431\q\sandbox\cds_tmp.csv')
#print(cds_tmp)

#cds_tmp.columns

# initialize list of lists
#name_cds = [['argentina', 'CDSI.AR.5Y.LAST_PRICE'], 
#            ['philippines', 'CDSI.PH.5Y.LAST_PRICE'],
#            ['czech republic','CDSI.CZ.5Y.LAST_PRICE'],
#            ['thailand','CDSI.TH.5Y.LAST_PRICE'],
#            ['turkey','CDSI.TR.5Y.LAST_PRICE'],
#            ['indonesia','CDSI.ID.5Y.LAST_PRICE'],
#           ['poland','CDSI.PL.5Y.LAST_PRICE'],
##           ['malaysia','CDSI.MY.5Y.LAST_PRICE'],
#           ['korea','CDSI.KR.5Y.LAST_PRICE'],
##          ['mexico','CDSI.MX.5Y.LAST_PRICE'],
#          ['south africa','CDSI.ZA.5Y.LAST_PRICE'],
##         ['israel','CDSI.IL.5Y.LAST_PRICE'],
#         ['hungary','CDSI.HU.5Y.LAST_PRICE'],
#         ['colombia','CDSI.CO.5Y.LAST_PRICE'],
#         ['chile','CDSI.CL.5Y.LAST_PRICE'],
##        ['brazil','CDSI.BR.5Y.LAST_PRICE'],
#        ['china','CDSI.CN.5Y.LAST_PRICE'],
#        ['russia','CDSI.RU.5Y.LAST_PRICE'],
#       ['peru','CDSI.PE.5Y.LAST_PRICE']]

cds_tmp.rename(columns={'CDSI.AR.5Y.LAST_PRICE':'ARS'}, inplace=True)
cds_tmp.rename(columns={'CDSI.PH.5Y.LAST_PRICE':'PHP'}, inplace=True)
cds_tmp.rename(columns={'CDSI.CZ.5Y.LAST_PRICE':'CZK'}, inplace=True)
cds_tmp.rename(columns={'CDSI.TH.5Y.LAST_PRICE':'THB'}, inplace=True)
cds_tmp.rename(columns={'CDSI.TR.5Y.LAST_PRICE':'TRY'}, inplace=True)
cds_tmp.rename(columns={'CDSI.ID.5Y.LAST_PRICE':'IDR'}, inplace=True)
cds_tmp.rename(columns={'CDSI.PL.5Y.LAST_PRICE':'PLN'}, inplace=True)
cds_tmp.rename(columns={'CDSI.MY.5Y.LAST_PRICE':'MYR'}, inplace=True)
cds_tmp.rename(columns={'CDSI.MX.5Y.LAST_PRICE':'MXN'}, inplace=True)
cds_tmp.rename(columns={'CDSI.KR.5Y.LAST_PRICE':'KRW'}, inplace=True)
cds_tmp.rename(columns={'CDSI.ZA.5Y.LAST_PRICE':'ZAR'}, inplace=True)
cds_tmp.rename(columns={'CDSI.IL.5Y.LAST_PRICE':'ILS'}, inplace=True)
cds_tmp.rename(columns={'CDSI.HU.5Y.LAST_PRICE':'HUF'}, inplace=True)
cds_tmp.rename(columns={'CDSI.CO.5Y.LAST_PRICE':'COP'}, inplace=True)
cds_tmp.rename(columns={'CDSI.CL.5Y.LAST_PRICE':'CLP'}, inplace=True)
cds_tmp.rename(columns={'CDSI.RU.5Y.LAST_PRICE':'RUB'}, inplace=True)
cds_tmp.rename(columns={'CDSI.PE.5Y.LAST_PRICE':'PEN'}, inplace=True)
cds_tmp.rename(columns={'CDSI.CN.5Y.LAST_PRICE':'CNH'}, inplace=True)
cds_tmp.rename(columns={'CDSI.BR.5Y.LAST_PRICE':'BRL'}, inplace=True)


#TRANSFORM ALL DATA
print(cds_tmp.columns)
print(cds_tmp.head())
# Create the pandas DataFrame
#name_cds = pd.DataFrame(name_cds, columns = ['country', 'ticker'])
cols =['ARS', 'PHP', 'CZK', 'THB', 'TRY', 'IDR', 'PLN', 'MYR', 'KRW','MXN', 'ZAR', 'ILS', 'HUF', 'COP', 'CLP', 'BRL', 'CNH', 'RUB', 'PEN']
####multiply to ahve the spread
cds_tmp[cols] = cds_tmp[cols].multiply(10000)
print(cds_tmp.head())
####mround to 
cds_tmp[cols] = cds_tmp[cols].round(1)
print(cds_tmp.head())
print(cds_tmp.tail())

Index(['Date', 'ARS', 'PHP', 'CZK', 'THB', 'TRY', 'IDR', 'PLN', 'MYR', 'KRW',
       'MXN', 'ZAR', 'ILS', 'HUF', 'COP', 'CLP', 'BRL', 'CNH', 'RUB', 'PEN'],
      dtype='object')
         Date     ARS     PHP     CZK     THB     TRY     IDR     PLN     MYR  \
0  2010-01-04  0.0890  0.0166  0.0095  0.0101  0.0183  0.0189  0.0134  0.0095
1  2010-01-05  0.0900  0.0164  0.0088  0.0098  0.0176  0.0189  0.0119  0.0091
2  2010-01-06  0.0925  0.0164  0.0086  0.0093  0.0176  0.0186  0.0120  0.0086
3  2010-01-07  0.0950  0.0164  0.0085  0.0088  0.0174  0.0186  0.0119  0.0081
4  2010-01-08  0.0965  0.0164  0.0084  0.0094  0.0174  0.0186  0.0120  0.0084

      KRW     MXN     ZAR     ILS     HUF     COP     CLP     BRL     CNH  \
0  0.0090  0.0125  0.0144  0.0124  0.0243  0.0135  0.0065  0.0116  0.0076
1  0.0087  0.0125  0.0134  0.0124  0.0227  0.0136  0.0065  0.0118  0.0073
2  0.0084  0.0124  0.0139  0.0124  0.0225  0.0133  0.0065  0.0116  0.0068
3  0.0079  0.0122  0.0134  0.0124  0.0217  0.0133  0.0065  0.0117  0.0063
4  0.0082  0.0123  0.0134  0.0124  0.0218  0.0131  0.0065  0.0115  0.0066

      RUB     PEN
0  0.0181  0.0118
1  0.0169  0.0119
2  0.0166  0.0117
3  0.0162  0.0117
4  0.0162  0.0115
         Date         ARS         PHP        CZK         THB         TRY  \
0  2010-01-04  890.000015  165.999997  94.999997  100.999996  183.000006
1  2010-01-05  900.000036  164.000001  88.000000   98.000001  175.999999
2  2010-01-06  925.000012  164.000001  86.000003   93.000000  175.999999
3  2010-01-07  949.999988  164.000001  85.000005   88.000000  174.000002
4  2010-01-08  965.000018  164.000001  83.999997   93.999999  174.000002

          IDR         PLN        MYR        KRW         MXN         ZAR  \
0  188.999996  133.999996  94.999997  89.999996  125.000002  143.999998
1  188.999996  119.000003  91.000004  87.000001  125.000002  133.999996
2  186.000001  120.000001  86.000003  83.999997  124.000004  138.999997
3  186.000001  119.000003  81.000002  78.999996  121.999998  133.999996
4  186.000001  120.000001  83.999997  82.000000  122.999996  133.999996

          ILS         HUF         COP        CLP         BRL        CNH  \
0  124.000004  242.999997  135.000004  65.000001  115.999999  76.000001
1  124.000004  227.000006  136.000002  65.000001  118.000004  73.000002
2  124.000004  225.000009  132.999998  65.000001  115.999999  68.000001
3  124.000004  217.000004  132.999998  65.000001  116.999997  63.000000
4  124.000004  218.000002  131.000001  65.000001  115.000000  66.000000

          RUB         PEN
0  181.000009  118.000004
1  168.999992  119.000003
2  165.999997  116.999997
3  162.000004  116.999997
4  162.000004  115.000000
         Date    ARS    PHP   CZK    THB    TRY    IDR    PLN   MYR   KRW  \
0  2010-01-04  890.0  166.0  95.0  101.0  183.0  189.0  134.0  95.0  90.0
1  2010-01-05  900.0  164.0  88.0   98.0  176.0  189.0  119.0  91.0  87.0
2  2010-01-06  925.0  164.0  86.0   93.0  176.0  186.0  120.0  86.0  84.0
3  2010-01-07  950.0  164.0  85.0   88.0  174.0  186.0  119.0  81.0  79.0
4  2010-01-08  965.0  164.0  84.0   94.0  174.0  186.0  120.0  84.0  82.0

     MXN    ZAR    ILS    HUF    COP   CLP    BRL   CNH    RUB    PEN
0  125.0  144.0  124.0  243.0  135.0  65.0  116.0  76.0  181.0  118.0
1  125.0  134.0  124.0  227.0  136.0  65.0  118.0  73.0  169.0  119.0
2  124.0  139.0  124.0  225.0  133.0  65.0  116.0  68.0  166.0  117.0
3  122.0  134.0  124.0  217.0  133.0  65.0  117.0  63.0  162.0  117.0
4  123.0  134.0  124.0  218.0  131.0  65.0  115.0  66.0  162.0  115.0
            Date     ARS   PHP   CZK   THB    TRY   IDR   PLN   MYR   KRW  \
2991  2021-10-07  2065.8  59.1  29.9  41.4  424.6  85.2  35.2  57.1  20.5
2992  2021-10-08  2103.9  61.6  29.9  42.1  434.0  87.7  35.3  59.6  20.7
2993  2021-10-11  2108.2  67.8  29.9  44.8  436.3  96.1  35.2  65.8  22.7
2994  2021-10-12  2149.2  65.8  29.9  43.3  439.6  93.3  35.2  63.3  22.0
2995  2021-10-13  2167.5  67.3  29.9  43.3  438.7  94.3  35.2  65.0  21.9

        MXN    ZAR   ILS   HUF    COP   CLP    BRL   CNH   RUB   PEN
2991   99.0  211.7  43.3  49.4  165.0  85.1  202.0  49.4  85.1  95.1
2992   99.5  210.7  43.3  49.4  165.0  87.1  204.0  52.4  86.1  96.0
2993   99.5  215.2  43.3  49.4  165.0  87.1  204.0  59.8  88.1  96.0
2994  103.0  218.6  43.3  49.4  168.5  90.1  208.9  56.3  90.1  97.0
2995  102.5  215.2  43.3  49.4  164.0  89.6  207.0  55.8  88.1  92.1

In [5]:
#sTEP 2 CREATE VARAIBLES
#rolling average
r=5
cds_tmp['ARS_avg5']=cds_tmp['ARS'].rolling(r).mean()
cds_tmp['PHP_avg5']=cds_tmp['PHP'].rolling(r).mean()
cds_tmp['CZK_avg5']=cds_tmp['CZK'].rolling(r).mean()
cds_tmp['THB_avg5']=cds_tmp['THB'].rolling(r).mean()
cds_tmp['TRY_avg5']=cds_tmp['TRY'].rolling(r).mean()
cds_tmp['IDR_avg5']=cds_tmp['IDR'].rolling(r).mean()
cds_tmp['PLN_avg5']=cds_tmp['PLN'].rolling(r).mean()
cds_tmp['MYR_avg5']=cds_tmp['MYR'].rolling(r).mean()
cds_tmp['MXN_avg5']=cds_tmp['MXN'].rolling(r).mean()
cds_tmp['KRW_avg5']=cds_tmp['KRW'].rolling(r).mean()
cds_tmp['ZAR_avg5']=cds_tmp['ZAR'].rolling(r).mean()
cds_tmp['ILS_avg5']=cds_tmp['ILS'].rolling(r).mean()
cds_tmp['HUF_avg5']=cds_tmp['HUF'].rolling(r).mean()
cds_tmp['COP_avg5']=cds_tmp['COP'].rolling(r).mean()
cds_tmp['CLP_avg5']=cds_tmp['CLP'].rolling(r).mean()
cds_tmp['RUB_avg5']=cds_tmp['RUB'].rolling(r).mean()
cds_tmp['PEN_avg5']=cds_tmp['PEN'].rolling(r).mean()
cds_tmp['CLP_avg5']=cds_tmp['CLP'].rolling(r).mean()
cds_tmp['CNH_avg5']=cds_tmp['CNH'].rolling(r).mean()
cds_tmp['BRL_avg5']=cds_tmp['BRL'].rolling(r).mean()
#cds_tmp.to_csv (r'K:\2020_2431\q\sandbox\cds_tec.csv', index = False, header=True)
cds_tmp.head()

r=15
cds_tmp['ARS_avg15']=cds_tmp['ARS'].rolling(r).mean()
cds_tmp['PHP_avg15']=cds_tmp['PHP'].rolling(r).mean()
cds_tmp['CZK_avg15']=cds_tmp['CZK'].rolling(r).mean()
cds_tmp['THB_avg15']=cds_tmp['THB'].rolling(r).mean()
cds_tmp['TRY_avg15']=cds_tmp['TRY'].rolling(r).mean()
cds_tmp['IDR_avg15']=cds_tmp['IDR'].rolling(r).mean()
cds_tmp['PLN_avg15']=cds_tmp['PLN'].rolling(r).mean()
cds_tmp['MYR_avg15']=cds_tmp['MYR'].rolling(r).mean()
cds_tmp['MXN_avg15']=cds_tmp['MXN'].rolling(r).mean()
cds_tmp['KRW_avg15']=cds_tmp['KRW'].rolling(r).mean()
cds_tmp['ZAR_avg15']=cds_tmp['ZAR'].rolling(r).mean()
cds_tmp['ILS_avg15']=cds_tmp['ILS'].rolling(r).mean()
cds_tmp['HUF_avg15']=cds_tmp['HUF'].rolling(r).mean()
cds_tmp['COP_avg15']=cds_tmp['COP'].rolling(r).mean()
cds_tmp['CLP_avg15']=cds_tmp['CLP'].rolling(r).mean()
cds_tmp['RUB_avg15']=cds_tmp['RUB'].rolling(r).mean()
cds_tmp['PEN_avg15']=cds_tmp['PEN'].rolling(r).mean()
cds_tmp['CLP_avg15']=cds_tmp['CLP'].rolling(r).mean()
cds_tmp['CNH_avg15']=cds_tmp['CNH'].rolling(r).mean()
cds_tmp['BRL_avg15']=cds_tmp['BRL'].rolling(r).mean()

r=30
cds_tmp['ARS_avg30']=cds_tmp['ARS'].rolling(r).mean()
cds_tmp['PHP_avg30']=cds_tmp['PHP'].rolling(r).mean()
cds_tmp['CZK_avg30']=cds_tmp['CZK'].rolling(r).mean()
cds_tmp['THB_avg30']=cds_tmp['THB'].rolling(r).mean()
cds_tmp['TRY_avg30']=cds_tmp['TRY'].rolling(r).mean()
cds_tmp['IDR_avg30']=cds_tmp['IDR'].rolling(r).mean()
cds_tmp['PLN_avg30']=cds_tmp['PLN'].rolling(r).mean()
cds_tmp['MYR_avg30']=cds_tmp['MYR'].rolling(r).mean()
cds_tmp['MXN_avg30']=cds_tmp['MXN'].rolling(r).mean()
cds_tmp['KRW_avg30']=cds_tmp['KRW'].rolling(r).mean()
cds_tmp['ZAR_avg30']=cds_tmp['ZAR'].rolling(r).mean()
cds_tmp['ILS_avg30']=cds_tmp['ILS'].rolling(r).mean()
cds_tmp['HUF_avg30']=cds_tmp['HUF'].rolling(r).mean()
cds_tmp['COP_avg30']=cds_tmp['COP'].rolling(r).mean()
cds_tmp['CLP_avg30']=cds_tmp['CLP'].rolling(r).mean()
cds_tmp['RUB_avg30']=cds_tmp['RUB'].rolling(r).mean()
cds_tmp['PEN_avg30']=cds_tmp['PEN'].rolling(r).mean()
cds_tmp['CLP_avg30']=cds_tmp['CLP'].rolling(r).mean()
cds_tmp['CNH_avg30']=cds_tmp['CNH'].rolling(r).mean()
cds_tmp['BRL_avg30']=cds_tmp['BRL'].rolling(r).mean()

r=90
cds_tmp['ARS_avg90']=cds_tmp['ARS'].rolling(r).mean()
cds_tmp['PHP_avg90']=cds_tmp['PHP'].rolling(r).mean()
cds_tmp['CZK_avg90']=cds_tmp['CZK'].rolling(r).mean()
cds_tmp['THB_avg90']=cds_tmp['THB'].rolling(r).mean()
cds_tmp['TRY_avg90']=cds_tmp['TRY'].rolling(r).mean()
cds_tmp['IDR_avg90']=cds_tmp['IDR'].rolling(r).mean()
cds_tmp['PLN_avg90']=cds_tmp['PLN'].rolling(r).mean()
cds_tmp['MYR_avg90']=cds_tmp['MYR'].rolling(r).mean()
cds_tmp['MXN_avg90']=cds_tmp['MXN'].rolling(r).mean()
cds_tmp['KRW_avg90']=cds_tmp['KRW'].rolling(r).mean()
cds_tmp['ZAR_avg90']=cds_tmp['ZAR'].rolling(r).mean()
cds_tmp['ILS_avg90']=cds_tmp['ILS'].rolling(r).mean()
cds_tmp['HUF_avg90']=cds_tmp['HUF'].rolling(r).mean()
cds_tmp['COP_avg90']=cds_tmp['COP'].rolling(r).mean()
cds_tmp['CLP_avg90']=cds_tmp['CLP'].rolling(r).mean()
cds_tmp['RUB_avg90']=cds_tmp['RUB'].rolling(r).mean()
cds_tmp['PEN_avg90']=cds_tmp['PEN'].rolling(r).mean()
cds_tmp['CLP_avg90']=cds_tmp['CLP'].rolling(r).mean()
cds_tmp['CNH_avg90']=cds_tmp['CNH'].rolling(r).mean()
cds_tmp['BRL_avg90']=cds_tmp['BRL'].rolling(r).mean()

#cds_tmp.to_csv (r'K:\2020_2431\q\sandbox\cds_tec.csv', index = False, header=True)
cds_tmp.head()

cols=['ARS_avg5','PHP_avg5','CZK_avg5','THB_avg5','TRY_avg5','IDR_avg5','PLN_avg5','MYR_avg5','MXN_avg5','KRW_avg5','ZAR_avg5','ILS_avg5','HUF_avg5','COP_avg5','CLP_avg5','RUB_avg5','PEN_avg5','CLP_avg5','CNH_avg5','BRL_avg5']
cds_tmp[cols] = cds_tmp[cols].round(1)
cols=['ARS_avg30','PHP_avg30','CZK_avg30','THB_avg30','TRY_avg30','IDR_avg30','PLN_avg30','MYR_avg30','MXN_avg30','KRW_avg30','ZAR_avg30','ILS_avg30','HUF_avg30','COP_avg30','CLP_avg30','RUB_avg30','PEN_avg30','CLP_avg30','CNH_avg30','BRL_avg30']
cds_tmp[cols] = cds_tmp[cols].round(1)
cds_tmp.head()

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,Date,ARS,PHP,CZK,THB,TRY,IDR,PLN,MYR,KRW,...,KRW_avg90,ZAR_avg90,ILS_avg90,HUF_avg90,COP_avg90,CLP_avg90,RUB_avg90,PEN_avg90,CNH_avg90,BRL_avg90
0,2010-01-04,890.0,166.0,95.0,101.0,183.0,189.0,134.0,95.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-01-05,900.0,164.0,88.0,98.0,176.0,189.0,119.0,91.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-06,925.0,164.0,86.0,93.0,176.0,186.0,120.0,86.0,84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-07,950.0,164.0,85.0,88.0,174.0,186.0,119.0,81.0,79.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-01-08,965.0,164.0,84.0,94.0,174.0,186.0,120.0,84.0,82.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#STEP3 CREATE STANADARD DEVIAITON
#rolling std
r=5
cds_tmp['ARS_std5']=cds_tmp['ARS'].rolling(r).std()
cds_tmp['PHP_std5']=cds_tmp['PHP'].rolling(r).std()
cds_tmp['CZK_std5']=cds_tmp['CZK'].rolling(r).std()
cds_tmp['THB_std5']=cds_tmp['THB'].rolling(r).std()
cds_tmp['TRY_std5']=cds_tmp['TRY'].rolling(r).std()
cds_tmp['IDR_std5']=cds_tmp['IDR'].rolling(r).std()
cds_tmp['PLN_std5']=cds_tmp['PLN'].rolling(r).std()
cds_tmp['MYR_std5']=cds_tmp['MYR'].rolling(r).std()
cds_tmp['MXN_std5']=cds_tmp['MXN'].rolling(r).std()
cds_tmp['KRW_std5']=cds_tmp['KRW'].rolling(r).std()
cds_tmp['ZAR_std5']=cds_tmp['ZAR'].rolling(r).std()
cds_tmp['ILS_std5']=cds_tmp['ILS'].rolling(r).std()
cds_tmp['HUF_std5']=cds_tmp['HUF'].rolling(r).std()
cds_tmp['COP_std5']=cds_tmp['COP'].rolling(r).std()
cds_tmp['CLP_std5']=cds_tmp['CLP'].rolling(r).std()
cds_tmp['RUB_std5']=cds_tmp['RUB'].rolling(r).std()
cds_tmp['PEN_std5']=cds_tmp['PEN'].rolling(r).std()
cds_tmp['CLP_std5']=cds_tmp['CLP'].rolling(r).std()
cds_tmp['CNH_std5']=cds_tmp['CNH'].rolling(r).std()
cds_tmp['BRL_std5']=cds_tmp['BRL'].rolling(r).std()
#cds_tmp.to_csv (r'K:\2020_2431\q\sandbox\cds_tec.csv', index = False, header=True)


r=15
cds_tmp['ARS_std15']=cds_tmp['ARS'].rolling(r).std()
cds_tmp['PHP_std15']=cds_tmp['PHP'].rolling(r).std()
cds_tmp['CZK_std15']=cds_tmp['CZK'].rolling(r).std()
cds_tmp['THB_std15']=cds_tmp['THB'].rolling(r).std()
cds_tmp['TRY_std15']=cds_tmp['TRY'].rolling(r).std()
cds_tmp['IDR_std15']=cds_tmp['IDR'].rolling(r).std()
cds_tmp['PLN_std15']=cds_tmp['PLN'].rolling(r).std()
cds_tmp['MYR_std15']=cds_tmp['MYR'].rolling(r).std()
cds_tmp['MXN_std15']=cds_tmp['MXN'].rolling(r).std()
cds_tmp['KRW_std15']=cds_tmp['KRW'].rolling(r).std()
cds_tmp['ZAR_std15']=cds_tmp['ZAR'].rolling(r).std()
cds_tmp['ILS_std15']=cds_tmp['ILS'].rolling(r).std()
cds_tmp['HUF_std15']=cds_tmp['HUF'].rolling(r).std()
cds_tmp['COP_std15']=cds_tmp['COP'].rolling(r).std()
cds_tmp['CLP_std15']=cds_tmp['CLP'].rolling(r).std()
cds_tmp['RUB_std15']=cds_tmp['RUB'].rolling(r).std()
cds_tmp['PEN_std15']=cds_tmp['PEN'].rolling(r).std()
cds_tmp['CLP_std15']=cds_tmp['CLP'].rolling(r).std()
cds_tmp['CNH_std15']=cds_tmp['CNH'].rolling(r).std()
cds_tmp['BRL_std15']=cds_tmp['BRL'].rolling(r).std()

r=30
cds_tmp['ARS_std30']=cds_tmp['ARS'].rolling(r).std()
cds_tmp['PHP_std30']=cds_tmp['PHP'].rolling(r).std()
cds_tmp['CZK_std30']=cds_tmp['CZK'].rolling(r).std()
cds_tmp['THB_std30']=cds_tmp['THB'].rolling(r).std()
cds_tmp['TRY_std30']=cds_tmp['TRY'].rolling(r).std()
cds_tmp['IDR_std30']=cds_tmp['IDR'].rolling(r).std()
cds_tmp['PLN_std30']=cds_tmp['PLN'].rolling(r).std()
cds_tmp['MYR_std30']=cds_tmp['MYR'].rolling(r).std()
cds_tmp['MXN_std30']=cds_tmp['MXN'].rolling(r).std()
cds_tmp['KRW_std30']=cds_tmp['KRW'].rolling(r).std()
cds_tmp['ZAR_std30']=cds_tmp['ZAR'].rolling(r).std()
cds_tmp['ILS_std30']=cds_tmp['ILS'].rolling(r).std()
cds_tmp['HUF_std30']=cds_tmp['HUF'].rolling(r).std()
cds_tmp['COP_std30']=cds_tmp['COP'].rolling(r).std()
cds_tmp['CLP_std30']=cds_tmp['CLP'].rolling(r).std()
cds_tmp['RUB_std30']=cds_tmp['RUB'].rolling(r).std()
cds_tmp['PEN_std30']=cds_tmp['PEN'].rolling(r).std()
cds_tmp['CLP_std30']=cds_tmp['CLP'].rolling(r).std()
cds_tmp['CNH_std30']=cds_tmp['CNH'].rolling(r).std()
cds_tmp['BRL_std30']=cds_tmp['BRL'].rolling(r).std()

r=90
cds_tmp['ARS_std90']=cds_tmp['ARS'].rolling(r).std()
cds_tmp['PHP_std90']=cds_tmp['PHP'].rolling(r).std()
cds_tmp['CZK_std90']=cds_tmp['CZK'].rolling(r).std()
cds_tmp['THB_std90']=cds_tmp['THB'].rolling(r).std()
cds_tmp['TRY_std90']=cds_tmp['TRY'].rolling(r).std()
cds_tmp['IDR_std90']=cds_tmp['IDR'].rolling(r).std()
cds_tmp['PLN_std90']=cds_tmp['PLN'].rolling(r).std()
cds_tmp['MYR_std90']=cds_tmp['MYR'].rolling(r).std()
cds_tmp['MXN_std90']=cds_tmp['MXN'].rolling(r).std()
cds_tmp['KRW_std90']=cds_tmp['KRW'].rolling(r).std()
cds_tmp['ZAR_std90']=cds_tmp['ZAR'].rolling(r).std()
cds_tmp['ILS_std90']=cds_tmp['ILS'].rolling(r).std()
cds_tmp['HUF_std90']=cds_tmp['HUF'].rolling(r).std()
cds_tmp['COP_std90']=cds_tmp['COP'].rolling(r).std()
cds_tmp['CLP_std90']=cds_tmp['CLP'].rolling(r).std()
cds_tmp['RUB_std90']=cds_tmp['RUB'].rolling(r).std()
cds_tmp['PEN_std90']=cds_tmp['PEN'].rolling(r).std()
cds_tmp['CLP_std90']=cds_tmp['CLP'].rolling(r).std()
cds_tmp['CNH_std90']=cds_tmp['CNH'].rolling(r).std()
cds_tmp['BRL_std90']=cds_tmp['BRL'].rolling(r).std()


cds_tmp.head()


cols=['ARS_std5','PHP_std5','CZK_std5','THB_std5','TRY_std5','IDR_std5','PLN_std5','MYR_std5','MXN_std5','KRW_std5','ZAR_std5','ILS_std5','HUF_std5','COP_std5','CLP_std5','RUB_std5','PEN_std5','CLP_std5','CNH_std5','BRL_std5']
cds_tmp[cols] = cds_tmp[cols].round(1)
cols=['ARS_std30','PHP_std30','CZK_std30','THB_std30','TRY_std30','IDR_std30','PLN_std30','MYR_std30','MXN_std30','KRW_std30','ZAR_std30','ILS_std30','HUF_std30','COP_std30','CLP_std30','RUB_std30','PEN_std30','CLP_std30','CNH_std30','BRL_std30']
cds_tmp[cols] = cds_tmp[cols].round(1)
cds_tmp.head()

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,Date,ARS,PHP,CZK,THB,TRY,IDR,PLN,MYR,KRW,...,KRW_std90,ZAR_std90,ILS_std90,HUF_std90,COP_std90,CLP_std90,RUB_std90,PEN_std90,CNH_std90,BRL_std90
0,2010-01-04,890.0,166.0,95.0,101.0,183.0,189.0,134.0,95.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-01-05,900.0,164.0,88.0,98.0,176.0,189.0,119.0,91.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-06,925.0,164.0,86.0,93.0,176.0,186.0,120.0,86.0,84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-07,950.0,164.0,85.0,88.0,174.0,186.0,119.0,81.0,79.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-01-08,965.0,164.0,84.0,94.0,174.0,186.0,120.0,84.0,82.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#STEP 4 CREATE DIFFERENCES
#difference in levels

#cds_tmp.to_csv (r'K:\2020_2431\q\sandbox\cds_tec.csv', index = False, header=True)
r=5
cds_tmp['ARS_dif5']=cds_tmp['ARS'].diff(r)
cds_tmp['PHP_dif5']=cds_tmp['PHP'].diff(r)
cds_tmp['CZK_dif5']=cds_tmp['CZK'].diff(r)
cds_tmp['THB_dif5']=cds_tmp['THB'].diff(r)
cds_tmp['TRY_dif5']=cds_tmp['TRY'].diff(r)
cds_tmp['IDR_dif5']=cds_tmp['IDR'].diff(r)
cds_tmp['PLN_dif5']=cds_tmp['PLN'].diff(r)
cds_tmp['MYR_dif5']=cds_tmp['MYR'].diff(r)
cds_tmp['MXN_dif5']=cds_tmp['MXN'].diff(r)
cds_tmp['KRW_dif5']=cds_tmp['KRW'].diff(r)
cds_tmp['ZAR_dif5']=cds_tmp['ZAR'].diff(r)
cds_tmp['ILS_dif5']=cds_tmp['ILS'].diff(r)
cds_tmp['HUF_dif5']=cds_tmp['HUF'].diff(r)
cds_tmp['COP_dif5']=cds_tmp['COP'].diff(r)
cds_tmp['CLP_dif5']=cds_tmp['CLP'].diff(r)
cds_tmp['RUB_dif5']=cds_tmp['RUB'].diff(r)
cds_tmp['PEN_dif5']=cds_tmp['PEN'].diff(r)
cds_tmp['CLP_dif5']=cds_tmp['CLP'].diff(r)
cds_tmp['CNH_dif5']=cds_tmp['CNH'].diff(r)
cds_tmp['BRL_dif5']=cds_tmp['BRL'].diff(r)


r=15
cds_tmp['ARS_dif15']=cds_tmp['ARS'].diff(r)
cds_tmp['PHP_dif15']=cds_tmp['PHP'].diff(r)
cds_tmp['CZK_dif15']=cds_tmp['CZK'].diff(r)
cds_tmp['THB_dif15']=cds_tmp['THB'].diff(r)
cds_tmp['TRY_dif15']=cds_tmp['TRY'].diff(r)
cds_tmp['IDR_dif15']=cds_tmp['IDR'].diff(r)
cds_tmp['PLN_dif15']=cds_tmp['PLN'].diff(r)
cds_tmp['MYR_dif15']=cds_tmp['MYR'].diff(r)
cds_tmp['MXN_dif15']=cds_tmp['MXN'].diff(r)
cds_tmp['KRW_dif15']=cds_tmp['KRW'].diff(r)
cds_tmp['ZAR_dif15']=cds_tmp['ZAR'].diff(r)
cds_tmp['ILS_dif15']=cds_tmp['ILS'].diff(r)
cds_tmp['HUF_dif15']=cds_tmp['HUF'].diff(r)
cds_tmp['COP_dif15']=cds_tmp['COP'].diff(r)
cds_tmp['CLP_dif15']=cds_tmp['CLP'].diff(r)
cds_tmp['RUB_dif15']=cds_tmp['RUB'].diff(r)
cds_tmp['PEN_dif15']=cds_tmp['PEN'].diff(r)
cds_tmp['CLP_dif15']=cds_tmp['CLP'].diff(r)
cds_tmp['CNH_dif15']=cds_tmp['CNH'].diff(r)
cds_tmp['BRL_dif15']=cds_tmp['BRL'].diff(r)


r=30
cds_tmp['ARS_dif30']=cds_tmp['ARS'].diff(r)
cds_tmp['PHP_dif30']=cds_tmp['PHP'].diff(r)
cds_tmp['CZK_dif30']=cds_tmp['CZK'].diff(r)
cds_tmp['THB_dif30']=cds_tmp['THB'].diff(r)
cds_tmp['TRY_dif30']=cds_tmp['TRY'].diff(r)
cds_tmp['IDR_dif30']=cds_tmp['IDR'].diff(r)
cds_tmp['PLN_dif30']=cds_tmp['PLN'].diff(r)
cds_tmp['MYR_dif30']=cds_tmp['MYR'].diff(r)
cds_tmp['MXN_dif30']=cds_tmp['MXN'].diff(r)
cds_tmp['KRW_dif30']=cds_tmp['KRW'].diff(r)
cds_tmp['ZAR_dif30']=cds_tmp['ZAR'].diff(r)
cds_tmp['ILS_dif30']=cds_tmp['ILS'].diff(r)
cds_tmp['HUF_dif30']=cds_tmp['HUF'].diff(r)
cds_tmp['COP_dif30']=cds_tmp['COP'].diff(r)
cds_tmp['CLP_dif30']=cds_tmp['CLP'].diff(r)
cds_tmp['RUB_dif30']=cds_tmp['RUB'].diff(r)
cds_tmp['PEN_dif30']=cds_tmp['PEN'].diff(r)
cds_tmp['CLP_dif30']=cds_tmp['CLP'].diff(r)
cds_tmp['CNH_dif30']=cds_tmp['CNH'].diff(r)
cds_tmp['BRL_dif30']=cds_tmp['BRL'].diff(r)


r=90
cds_tmp['ARS_dif90']=cds_tmp['ARS'].diff(r)
cds_tmp['PHP_dif90']=cds_tmp['PHP'].diff(r)
cds_tmp['CZK_dif90']=cds_tmp['CZK'].diff(r)
cds_tmp['THB_dif90']=cds_tmp['THB'].diff(r)
cds_tmp['TRY_dif90']=cds_tmp['TRY'].diff(r)
cds_tmp['IDR_dif90']=cds_tmp['IDR'].diff(r)
cds_tmp['PLN_dif90']=cds_tmp['PLN'].diff(r)
cds_tmp['MYR_dif90']=cds_tmp['MYR'].diff(r)
cds_tmp['MXN_dif90']=cds_tmp['MXN'].diff(r)
cds_tmp['KRW_dif90']=cds_tmp['KRW'].diff(r)
cds_tmp['ZAR_dif90']=cds_tmp['ZAR'].diff(r)
cds_tmp['ILS_dif90']=cds_tmp['ILS'].diff(r)
cds_tmp['HUF_dif90']=cds_tmp['HUF'].diff(r)
cds_tmp['COP_dif90']=cds_tmp['COP'].diff(r)
cds_tmp['CLP_dif90']=cds_tmp['CLP'].diff(r)
cds_tmp['RUB_dif90']=cds_tmp['RUB'].diff(r)
cds_tmp['PEN_dif90']=cds_tmp['PEN'].diff(r)
cds_tmp['CLP_dif90']=cds_tmp['CLP'].diff(r)
cds_tmp['CNH_dif90']=cds_tmp['CNH'].diff(r)
cds_tmp['BRL_dif90']=cds_tmp['BRL'].diff(r)


cols=['ARS_dif5','PHP_dif5','CZK_dif5','THB_dif5','TRY_dif5','IDR_dif5','PLN_dif5','MYR_dif5','MXN_dif5','KRW_dif5','ZAR_dif5','ILS_dif5','HUF_dif5','COP_dif5','CLP_dif5','RUB_dif5','PEN_dif5','CLP_dif5','CNH_dif5','BRL_dif5']
cds_tmp[cols] = cds_tmp[cols].round(1)
cols=['ARS_dif30','PHP_dif30','CZK_dif30','THB_dif30','TRY_dif30','IDR_dif30','PLN_dif30','MYR_dif30','MXN_dif30','KRW_dif30','ZAR_dif30','ILS_dif30','HUF_dif30','COP_dif30','CLP_dif30','RUB_dif30','PEN_dif30','CLP_dif30','CNH_dif30','BRL_dif30']
cds_tmp[cols] = cds_tmp[cols].round(1)
cds_tmp.head()

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,Date,ARS,PHP,CZK,THB,TRY,IDR,PLN,MYR,KRW,...,KRW_dif90,ZAR_dif90,ILS_dif90,HUF_dif90,COP_dif90,CLP_dif90,RUB_dif90,PEN_dif90,CNH_dif90,BRL_dif90
0,2010-01-04,890.0,166.0,95.0,101.0,183.0,189.0,134.0,95.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-01-05,900.0,164.0,88.0,98.0,176.0,189.0,119.0,91.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-06,925.0,164.0,86.0,93.0,176.0,186.0,120.0,86.0,84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-07,950.0,164.0,85.0,88.0,174.0,186.0,119.0,81.0,79.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-01-08,965.0,164.0,84.0,94.0,174.0,186.0,120.0,84.0,82.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#STEP 6 CREATE MAX AND MINS
#max


r=5
cds_tmp['ARS_mx5']=cds_tmp['ARS'].rolling(r,min_periods=1).max()
cds_tmp['PHP_mx5']=cds_tmp['PHP'].rolling(r,min_periods=1).max()
cds_tmp['CZK_mx5']=cds_tmp['CZK'].rolling(r,min_periods=1).max()
cds_tmp['THB_mx5']=cds_tmp['THB'].rolling(r,min_periods=1).max()
cds_tmp['TRY_mx5']=cds_tmp['TRY'].rolling(r,min_periods=1).max()
cds_tmp['IDR_mx5']=cds_tmp['IDR'].rolling(r,min_periods=1).max()
cds_tmp['PLN_mx5']=cds_tmp['PLN'].rolling(r,min_periods=1).max()
cds_tmp['MYR_mx5']=cds_tmp['MYR'].rolling(r,min_periods=1).max()
cds_tmp['MXN_mx5']=cds_tmp['MXN'].rolling(r,min_periods=1).max()
cds_tmp['KRW_mx5']=cds_tmp['KRW'].rolling(r,min_periods=1).max()
cds_tmp['ZAR_mx5']=cds_tmp['ZAR'].rolling(r,min_periods=1).max()
cds_tmp['ILS_mx5']=cds_tmp['ILS'].rolling(r,min_periods=1).max()
cds_tmp['HUF_mx5']=cds_tmp['HUF'].rolling(r,min_periods=1).max()
cds_tmp['COP_mx5']=cds_tmp['COP'].rolling(r,min_periods=1).max()
cds_tmp['CLP_mx5']=cds_tmp['CLP'].rolling(r,min_periods=1).max()
cds_tmp['RUB_mx5']=cds_tmp['RUB'].rolling(r,min_periods=1).max()
cds_tmp['PEN_mx5']=cds_tmp['PEN'].rolling(r,min_periods=1).max()
cds_tmp['CNH_mx5']=cds_tmp['CNH'].rolling(r,min_periods=1).max()
cds_tmp['BRL_mx5']=cds_tmp['BRL'].rolling(r,min_periods=1).max()

r=15
cds_tmp['ARS_mx15']=cds_tmp['ARS'].rolling(r,min_periods=1).max()
cds_tmp['PHP_mx15']=cds_tmp['PHP'].rolling(r,min_periods=1).max()
cds_tmp['CZK_mx15']=cds_tmp['CZK'].rolling(r,min_periods=1).max()
cds_tmp['THB_mx15']=cds_tmp['THB'].rolling(r,min_periods=1).max()
cds_tmp['TRY_mx15']=cds_tmp['TRY'].rolling(r,min_periods=1).max()
cds_tmp['IDR_mx15']=cds_tmp['IDR'].rolling(r,min_periods=1).max()
cds_tmp['PLN_mx15']=cds_tmp['PLN'].rolling(r,min_periods=1).max()
cds_tmp['MYR_mx15']=cds_tmp['MYR'].rolling(r,min_periods=1).max()
cds_tmp['MXN_mx15']=cds_tmp['MXN'].rolling(r,min_periods=1).max()
cds_tmp['KRW_mx15']=cds_tmp['KRW'].rolling(r,min_periods=1).max()
cds_tmp['ZAR_mx15']=cds_tmp['ZAR'].rolling(r,min_periods=1).max()
cds_tmp['ILS_mx15']=cds_tmp['ILS'].rolling(r,min_periods=1).max()
cds_tmp['HUF_mx15']=cds_tmp['HUF'].rolling(r,min_periods=1).max()
cds_tmp['COP_mx15']=cds_tmp['COP'].rolling(r,min_periods=1).max()
cds_tmp['CLP_mx15']=cds_tmp['CLP'].rolling(r,min_periods=1).max()
cds_tmp['RUB_mx15']=cds_tmp['RUB'].rolling(r,min_periods=1).max()
cds_tmp['PEN_mx15']=cds_tmp['PEN'].rolling(r,min_periods=1).max()
cds_tmp['CNH_mx15']=cds_tmp['CNH'].rolling(r,min_periods=1).max()
cds_tmp['BRL_mx15']=cds_tmp['BRL'].rolling(r,min_periods=1).max()

r=30
cds_tmp['ARS_mx30']=cds_tmp['ARS'].rolling(r,min_periods=1).max()
cds_tmp['PHP_mx30']=cds_tmp['PHP'].rolling(r,min_periods=1).max()
cds_tmp['CZK_mx30']=cds_tmp['CZK'].rolling(r,min_periods=1).max()
cds_tmp['THB_mx30']=cds_tmp['THB'].rolling(r,min_periods=1).max()
cds_tmp['TRY_mx30']=cds_tmp['TRY'].rolling(r,min_periods=1).max()
cds_tmp['IDR_mx30']=cds_tmp['IDR'].rolling(r,min_periods=1).max()
cds_tmp['PLN_mx30']=cds_tmp['PLN'].rolling(r,min_periods=1).max()
cds_tmp['MYR_mx30']=cds_tmp['MYR'].rolling(r,min_periods=1).max()
cds_tmp['MXN_mx30']=cds_tmp['MXN'].rolling(r,min_periods=1).max()
cds_tmp['KRW_mx30']=cds_tmp['KRW'].rolling(r,min_periods=1).max()
cds_tmp['ZAR_mx30']=cds_tmp['ZAR'].rolling(r,min_periods=1).max()
cds_tmp['ILS_mx30']=cds_tmp['ILS'].rolling(r,min_periods=1).max()
cds_tmp['HUF_mx30']=cds_tmp['HUF'].rolling(r,min_periods=1).max()
cds_tmp['COP_mx30']=cds_tmp['COP'].rolling(r,min_periods=1).max()
cds_tmp['CLP_mx30']=cds_tmp['CLP'].rolling(r,min_periods=1).max()
cds_tmp['RUB_mx30']=cds_tmp['RUB'].rolling(r,min_periods=1).max()
cds_tmp['PEN_mx30']=cds_tmp['PEN'].rolling(r,min_periods=1).max()
cds_tmp['CNH_mx30']=cds_tmp['CNH'].rolling(r,min_periods=1).max()
cds_tmp['BRL_mx30']=cds_tmp['BRL'].rolling(r,min_periods=1).max()


r=90
cds_tmp['ARS_mx90']=cds_tmp['ARS'].rolling(r,min_periods=1).max()
cds_tmp['PHP_mx90']=cds_tmp['PHP'].rolling(r,min_periods=1).max()
cds_tmp['CZK_mx90']=cds_tmp['CZK'].rolling(r,min_periods=1).max()
cds_tmp['THB_mx90']=cds_tmp['THB'].rolling(r,min_periods=1).max()
cds_tmp['TRY_mx90']=cds_tmp['TRY'].rolling(r,min_periods=1).max()
cds_tmp['IDR_mx90']=cds_tmp['IDR'].rolling(r,min_periods=1).max()
cds_tmp['PLN_mx90']=cds_tmp['PLN'].rolling(r,min_periods=1).max()
cds_tmp['MYR_mx90']=cds_tmp['MYR'].rolling(r,min_periods=1).max()
cds_tmp['MXN_mx90']=cds_tmp['MXN'].rolling(r,min_periods=1).max()
cds_tmp['KRW_mx90']=cds_tmp['KRW'].rolling(r,min_periods=1).max()
cds_tmp['ZAR_mx90']=cds_tmp['ZAR'].rolling(r,min_periods=1).max()
cds_tmp['ILS_mx90']=cds_tmp['ILS'].rolling(r,min_periods=1).max()
cds_tmp['HUF_mx90']=cds_tmp['HUF'].rolling(r,min_periods=1).max()
cds_tmp['COP_mx90']=cds_tmp['COP'].rolling(r,min_periods=1).max()
cds_tmp['CLP_mx90']=cds_tmp['CLP'].rolling(r,min_periods=1).max()
cds_tmp['RUB_mx90']=cds_tmp['RUB'].rolling(r,min_periods=1).max()
cds_tmp['PEN_mx90']=cds_tmp['PEN'].rolling(r,min_periods=1).max()
cds_tmp['CNH_mx90']=cds_tmp['CNH'].rolling(r,min_periods=1).max()
cds_tmp['BRL_mx90']=cds_tmp['BRL'].rolling(r,min_periods=1).max()

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [9]:
#STEP 7 CREATE MINS
#min

r=5
cds_tmp['ARS_mn5']=cds_tmp['ARS'].rolling(r,min_periods=1).min()
cds_tmp['PHP_mn5']=cds_tmp['PHP'].rolling(r,min_periods=1).min()
cds_tmp['CZK_mn5']=cds_tmp['CZK'].rolling(r,min_periods=1).min()
cds_tmp['THB_mn5']=cds_tmp['THB'].rolling(r,min_periods=1).min()
cds_tmp['TRY_mn5']=cds_tmp['TRY'].rolling(r,min_periods=1).min()
cds_tmp['IDR_mn5']=cds_tmp['IDR'].rolling(r,min_periods=1).min()
cds_tmp['PLN_mn5']=cds_tmp['PLN'].rolling(r,min_periods=1).min()
cds_tmp['MYR_mn5']=cds_tmp['MYR'].rolling(r,min_periods=1).min()
cds_tmp['MXN_mn5']=cds_tmp['MXN'].rolling(r,min_periods=1).min()
cds_tmp['KRW_mn5']=cds_tmp['KRW'].rolling(r,min_periods=1).min()
cds_tmp['ZAR_mn5']=cds_tmp['ZAR'].rolling(r,min_periods=1).min()
cds_tmp['ILS_mn5']=cds_tmp['ILS'].rolling(r,min_periods=1).min()
cds_tmp['HUF_mn5']=cds_tmp['HUF'].rolling(r,min_periods=1).min()
cds_tmp['COP_mn5']=cds_tmp['COP'].rolling(r,min_periods=1).min()
cds_tmp['CLP_mn5']=cds_tmp['CLP'].rolling(r,min_periods=1).min()
cds_tmp['RUB_mn5']=cds_tmp['RUB'].rolling(r,min_periods=1).min()
cds_tmp['PEN_mn5']=cds_tmp['PEN'].rolling(r,min_periods=1).min()
cds_tmp['CNH_mn5']=cds_tmp['CNH'].rolling(r,min_periods=1).min()
cds_tmp['BRL_mn5']=cds_tmp['BRL'].rolling(r,min_periods=1).min()

r=15
cds_tmp['ARS_mn15']=cds_tmp['ARS'].rolling(r,min_periods=1).min()
cds_tmp['PHP_mn15']=cds_tmp['PHP'].rolling(r,min_periods=1).min()
cds_tmp['CZK_mn15']=cds_tmp['CZK'].rolling(r,min_periods=1).min()
cds_tmp['THB_mn15']=cds_tmp['THB'].rolling(r,min_periods=1).min()
cds_tmp['TRY_mn15']=cds_tmp['TRY'].rolling(r,min_periods=1).min()
cds_tmp['IDR_mn15']=cds_tmp['IDR'].rolling(r,min_periods=1).min()
cds_tmp['PLN_mn15']=cds_tmp['PLN'].rolling(r,min_periods=1).min()
cds_tmp['MYR_mn15']=cds_tmp['MYR'].rolling(r,min_periods=1).min()
cds_tmp['MXN_mn15']=cds_tmp['MXN'].rolling(r,min_periods=1).min()
cds_tmp['KRW_mn15']=cds_tmp['KRW'].rolling(r,min_periods=1).min()
cds_tmp['ZAR_mn15']=cds_tmp['ZAR'].rolling(r,min_periods=1).min()
cds_tmp['ILS_mn15']=cds_tmp['ILS'].rolling(r,min_periods=1).min()
cds_tmp['HUF_mn15']=cds_tmp['HUF'].rolling(r,min_periods=1).min()
cds_tmp['COP_mn15']=cds_tmp['COP'].rolling(r,min_periods=1).min()
cds_tmp['CLP_mn15']=cds_tmp['CLP'].rolling(r,min_periods=1).min()
cds_tmp['RUB_mn15']=cds_tmp['RUB'].rolling(r,min_periods=1).min()
cds_tmp['PEN_mn15']=cds_tmp['PEN'].rolling(r,min_periods=1).min()
cds_tmp['CNH_mn15']=cds_tmp['CNH'].rolling(r,min_periods=1).min()
cds_tmp['BRL_mn15']=cds_tmp['BRL'].rolling(r,min_periods=1).min()

r=30
cds_tmp['ARS_mn30']=cds_tmp['ARS'].rolling(r,min_periods=1).min()
cds_tmp['PHP_mn30']=cds_tmp['PHP'].rolling(r,min_periods=1).min()
cds_tmp['CZK_mn30']=cds_tmp['CZK'].rolling(r,min_periods=1).min()
cds_tmp['THB_mn30']=cds_tmp['THB'].rolling(r,min_periods=1).min()
cds_tmp['TRY_mn30']=cds_tmp['TRY'].rolling(r,min_periods=1).min()
cds_tmp['IDR_mn30']=cds_tmp['IDR'].rolling(r,min_periods=1).min()
cds_tmp['PLN_mn30']=cds_tmp['PLN'].rolling(r,min_periods=1).min()
cds_tmp['MYR_mn30']=cds_tmp['MYR'].rolling(r,min_periods=1).min()
cds_tmp['MXN_mn30']=cds_tmp['MXN'].rolling(r,min_periods=1).min()
cds_tmp['KRW_mn30']=cds_tmp['KRW'].rolling(r,min_periods=1).min()
cds_tmp['ZAR_mn30']=cds_tmp['ZAR'].rolling(r,min_periods=1).min()
cds_tmp['ILS_mn30']=cds_tmp['ILS'].rolling(r,min_periods=1).min()
cds_tmp['HUF_mn30']=cds_tmp['HUF'].rolling(r,min_periods=1).min()
cds_tmp['COP_mn30']=cds_tmp['COP'].rolling(r,min_periods=1).min()
cds_tmp['CLP_mn30']=cds_tmp['CLP'].rolling(r,min_periods=1).min()
cds_tmp['RUB_mn30']=cds_tmp['RUB'].rolling(r,min_periods=1).min()
cds_tmp['PEN_mn30']=cds_tmp['PEN'].rolling(r,min_periods=1).min()
cds_tmp['CNH_mn30']=cds_tmp['CNH'].rolling(r,min_periods=1).min()
cds_tmp['BRL_mn30']=cds_tmp['BRL'].rolling(r,min_periods=1).min()


r=90
cds_tmp['ARS_mn90']=cds_tmp['ARS'].rolling(r,min_periods=1).min()
cds_tmp['PHP_mn90']=cds_tmp['PHP'].rolling(r,min_periods=1).min()
cds_tmp['CZK_mn90']=cds_tmp['CZK'].rolling(r,min_periods=1).min()
cds_tmp['THB_mn90']=cds_tmp['THB'].rolling(r,min_periods=1).min()
cds_tmp['TRY_mn90']=cds_tmp['TRY'].rolling(r,min_periods=1).min()
cds_tmp['IDR_mn90']=cds_tmp['IDR'].rolling(r,min_periods=1).min()
cds_tmp['PLN_mn90']=cds_tmp['PLN'].rolling(r,min_periods=1).min()
cds_tmp['MYR_mn90']=cds_tmp['MYR'].rolling(r,min_periods=1).min()
cds_tmp['MXN_mn90']=cds_tmp['MXN'].rolling(r,min_periods=1).min()
cds_tmp['KRW_mn90']=cds_tmp['KRW'].rolling(r,min_periods=1).min()
cds_tmp['ZAR_mn90']=cds_tmp['ZAR'].rolling(r,min_periods=1).min()
cds_tmp['ILS_mn90']=cds_tmp['ILS'].rolling(r,min_periods=1).min()
cds_tmp['HUF_mn90']=cds_tmp['HUF'].rolling(r,min_periods=1).min()
cds_tmp['COP_mn90']=cds_tmp['COP'].rolling(r,min_periods=1).min()
cds_tmp['CLP_mn90']=cds_tmp['CLP'].rolling(r,min_periods=1).min()
cds_tmp['RUB_mn90']=cds_tmp['RUB'].rolling(r,min_periods=1).min()
cds_tmp['PEN_mn90']=cds_tmp['PEN'].rolling(r,min_periods=1).min()
cds_tmp['CNH_mn90']=cds_tmp['CNH'].rolling(r,min_periods=1).min()
cds_tmp['BRL_mn90']=cds_tmp['BRL'].rolling(r,min_periods=1).min()

#cds_tmp.to_csv (r'K:\2020_2431\q\sandbox\cds_tec.csv', index = False, header=True)

In [10]:
#STEP 8 CREATE Z SCORES
#PARAMETERES 90 180 360
#zscores
N = 90
cds_tmp['ARS_z90']=zscore(cds_tmp['ARS'], N)
cds_tmp['PHP_z90']=zscore(cds_tmp['PHP'], N)
cds_tmp['CZK_z90']=zscore(cds_tmp['CZK'], N)
cds_tmp['THB_z90']=zscore(cds_tmp['THB'], N)
cds_tmp['TRY_z90']=zscore(cds_tmp['TRY'], N)
cds_tmp['IDR_z90']=zscore(cds_tmp['IDR'], N)
cds_tmp['PLN_z90']=zscore(cds_tmp['PLN'], N)
cds_tmp['MYR_z90']=zscore(cds_tmp['MYR'], N)
cds_tmp['MXN_z90']=zscore(cds_tmp['MXN'], N)
cds_tmp['KRW_z90']=zscore(cds_tmp['KRW'], N)
cds_tmp['ZAR_z90']=zscore(cds_tmp['ZAR'], N)
cds_tmp['ILS_z90']=zscore(cds_tmp['ILS'], N)
cds_tmp['HUF_z90']=zscore(cds_tmp['HUF'], N)
cds_tmp['COP_z90']=zscore(cds_tmp['COP'], N)
cds_tmp['CLP_z90']=zscore(cds_tmp['CLP'], N)
cds_tmp['BRL_z90']=zscore(cds_tmp['BRL'], N)
cds_tmp['CNH_z90']=zscore(cds_tmp['CNH'], N)
cds_tmp['RUB_z90']=zscore(cds_tmp['RUB'], N)
cds_tmp['PEN_z90']=zscore(cds_tmp['PEN'], N)


N = 180
cds_tmp['ARS_z180']=zscore(cds_tmp['ARS'], N)
cds_tmp['PHP_z180']=zscore(cds_tmp['PHP'], N)
cds_tmp['CZK_z180']=zscore(cds_tmp['CZK'], N)
cds_tmp['THB_z180']=zscore(cds_tmp['THB'], N)
cds_tmp['TRY_z180']=zscore(cds_tmp['TRY'], N)
cds_tmp['IDR_z180']=zscore(cds_tmp['IDR'], N)
cds_tmp['PLN_z180']=zscore(cds_tmp['PLN'], N)
cds_tmp['MYR_z180']=zscore(cds_tmp['MYR'], N)
cds_tmp['MXN_z180']=zscore(cds_tmp['MXN'], N)
cds_tmp['KRW_z180']=zscore(cds_tmp['KRW'], N)
cds_tmp['ZAR_z180']=zscore(cds_tmp['ZAR'], N)
cds_tmp['ILS_z180']=zscore(cds_tmp['ILS'], N)
cds_tmp['HUF_z180']=zscore(cds_tmp['HUF'], N)
cds_tmp['COP_z180']=zscore(cds_tmp['COP'], N)
cds_tmp['CLP_z180']=zscore(cds_tmp['CLP'], N)
cds_tmp['BRL_z180']=zscore(cds_tmp['BRL'], N)
cds_tmp['CNH_z180']=zscore(cds_tmp['CNH'], N)
cds_tmp['RUB_z180']=zscore(cds_tmp['RUB'], N)
cds_tmp['PEN_z180']=zscore(cds_tmp['PEN'], N)


N = 360
cds_tmp['ARS_z360']=zscore(cds_tmp['ARS'], N)
cds_tmp['PHP_z360']=zscore(cds_tmp['PHP'], N)
cds_tmp['CZK_z360']=zscore(cds_tmp['CZK'], N)
cds_tmp['THB_z360']=zscore(cds_tmp['THB'], N)
cds_tmp['TRY_z360']=zscore(cds_tmp['TRY'], N)
cds_tmp['IDR_z360']=zscore(cds_tmp['IDR'], N)
cds_tmp['PLN_z360']=zscore(cds_tmp['PLN'], N)
cds_tmp['MYR_z360']=zscore(cds_tmp['MYR'], N)
cds_tmp['MXN_z360']=zscore(cds_tmp['MXN'], N)
cds_tmp['KRW_z360']=zscore(cds_tmp['KRW'], N)
cds_tmp['ZAR_z360']=zscore(cds_tmp['ZAR'], N)
cds_tmp['ILS_z360']=zscore(cds_tmp['ILS'], N)
cds_tmp['HUF_z360']=zscore(cds_tmp['HUF'], N)
cds_tmp['COP_z360']=zscore(cds_tmp['COP'], N)
cds_tmp['CLP_z360']=zscore(cds_tmp['CLP'], N)
cds_tmp['BRL_z360']=zscore(cds_tmp['BRL'], N)
cds_tmp['CNH_z360']=zscore(cds_tmp['CNH'], N)
cds_tmp['RUB_z360']=zscore(cds_tmp['RUB'], N)
cds_tmp['PEN_z360']=zscore(cds_tmp['PEN'], N)


cols=['ARS_z90','PHP_z90','CZK_z90','THB_z90','TRY_z90','IDR_z90','PLN_z90','MYR_z90','MXN_z90','KRW_z90','ZAR_z90','ILS_z90','HUF_z90','COP_z90','CLP_z90','RUB_z90','PEN_z90','CLP_z90','CNH_z90','BRL_z90']
cds_tmp[cols] = cds_tmp[cols].round(2)
cols=['ARS_z180','PHP_z180','CZK_z180','THB_z180','TRY_z180','IDR_z180','PLN_z180','MYR_z180','MXN_z180','KRW_z180','ZAR_z180','ILS_z180','HUF_z180','COP_z180','CLP_z180','RUB_z180','PEN_z180','CLP_z180','CNH_z180','BRL_z180']
cds_tmp[cols] = cds_tmp[cols].round(2)
cols=['ARS_z360','PHP_z360','CZK_z360','THB_z360','TRY_z360','IDR_z360','PLN_z360','MYR_z360','MXN_z360','KRW_z360','ZAR_z360','ILS_z360','HUF_z360','COP_z360','CLP_z360','RUB_z360','PEN_z360','CLP_z360','CNH_z360','BRL_z360']
cds_tmp[cols] = cds_tmp[cols].round(2)
cds_tmp.head()

,Date,ARS,PHP,CZK,THB,TRY,IDR,PLN,MYR,KRW,...,KRW_z360,ZAR_z360,ILS_z360,HUF_z360,COP_z360,CLP_z360,BRL_z360,CNH_z360,RUB_z360,PEN_z360
0,2010-01-04,890.0,166.0,95.0,101.0,183.0,189.0,134.0,95.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-01-05,900.0,164.0,88.0,98.0,176.0,189.0,119.0,91.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-06,925.0,164.0,86.0,93.0,176.0,186.0,120.0,86.0,84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-07,950.0,164.0,85.0,88.0,174.0,186.0,119.0,81.0,79.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-01-08,965.0,164.0,84.0,94.0,174.0,186.0,120.0,84.0,82.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#STEP 10 CREATE REGIONAL cds
#REGIONAL 

#REGIONAL CDS

cds_tmp['BRL_reg']=cds_tmp[['COP','MXN','PEN','CLP']].mean(axis=1)
cds_tmp['CLP_reg']=cds_tmp[['COP','MXN','PEN','BRL']].mean(axis=1)  
cds_tmp['COP_reg']=cds_tmp[['CLP','MXN','PEN','BRL']].mean(axis=1)  
cds_tmp['PEN_reg']=cds_tmp[['CLP','MXN','COP','BRL']].mean(axis=1) 
cds_tmp['MXN_reg']=cds_tmp[['CLP','PEN','COP','BRL']].mean(axis=1)    

cds_tmp['CZK_reg']=cds_tmp[['HUF','RUB','ZAR','ILS','PLN','TRY']].mean(axis=1)
cds_tmp['HUF_reg']=cds_tmp[['CZK','RUB','ZAR','ILS','PLN','TRY']].mean(axis=1)
cds_tmp['RUB_reg']=cds_tmp[['CZK','HUF','ZAR','ILS','PLN','TRY']].mean(axis=1)
cds_tmp['ZAR_reg']=cds_tmp[['CZK','HUF','RUB','ILS','PLN','TRY']].mean(axis=1)
cds_tmp['PLN_reg']=cds_tmp[['CZK','HUF','RUB','ILS','ZAR','TRY']].mean(axis=1)
cds_tmp['ILS_reg']=cds_tmp[['CZK','HUF','RUB','PLN','ZAR','TRY']].mean(axis=1) 
cds_tmp['TRY_reg']=cds_tmp[['CZK','HUF','RUB','PLN','ZAR','ILS']].mean(axis=1) 
      
cds_tmp['PHP_reg']=cds_tmp[['THB','CNH','IDR','MYR','KRW']].mean(axis=1) 
cds_tmp['THB_reg']=cds_tmp[['PHP','CNH','IDR','MYR','KRW']].mean(axis=1) 
cds_tmp['CNH_reg']=cds_tmp[['THB','PHP','IDR','MYR','KRW']].mean(axis=1) 
cds_tmp['KRW_reg']=cds_tmp[['THB','CNH','IDR','MYR','PHP']].mean(axis=1) 
cds_tmp['MYR_reg']=cds_tmp[['THB','CNH','IDR','PHP','KRW']].mean(axis=1) 
cds_tmp['IDR_reg']=cds_tmp[['THB','CNH','MYR','PHP','KRW']].mean(axis=1) 


cols=['BRL_reg','CLP_reg','COP_reg','PEN_reg','MXN_reg','CZK_reg','HUF_reg','RUB_reg','ZAR_reg','PLN_reg','ILS_reg','TRY_reg', 'PHP_reg','THB_reg','CNH_reg','KRW_reg','MYR_reg','IDR_reg']
cds_tmp[cols] = cds_tmp[cols].round(1)
cds_tmp.head()

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,Date,ARS,PHP,CZK,THB,TRY,IDR,PLN,MYR,KRW,...,ZAR_reg,PLN_reg,ILS_reg,TRY_reg,PHP_reg,THB_reg,CNH_reg,KRW_reg,MYR_reg,IDR_reg
0,2010-01-04,890.0,166.0,95.0,101.0,183.0,189.0,134.0,95.0,90.0,...,160.0,161.7,163.3,153.5,110.2,123.2,128.2,125.4,124.4,105.6
1,2010-01-05,900.0,164.0,88.0,98.0,176.0,189.0,119.0,91.0,87.0,...,150.5,153.0,152.2,143.5,107.6,120.8,125.8,123.0,122.2,102.6
2,2010-01-06,925.0,164.0,86.0,93.0,176.0,186.0,120.0,86.0,84.0,...,149.5,152.7,152.0,143.3,103.4,117.6,122.6,119.4,119.0,99.0
3,2010-01-07,950.0,164.0,85.0,88.0,174.0,186.0,119.0,81.0,79.0,...,146.8,149.3,148.5,140.2,99.4,114.6,119.6,116.4,116.0,95.0
4,2010-01-08,965.0,164.0,84.0,94.0,174.0,186.0,120.0,84.0,82.0,...,147.0,149.3,148.7,140.3,102.4,116.4,122.0,118.8,118.4,98.0

In [12]:
#STEPO 11 RECREATE cds COLUMNS FOR THE FUTURE LOOPS
cds_tmp['ARS_cds']=(cds_tmp['ARS'])
cds_tmp['PHP_cds']=(cds_tmp['PHP'])
cds_tmp['CZK_cds']=(cds_tmp['CZK'])
cds_tmp['THB_cds']=(cds_tmp['THB'])
cds_tmp['TRY_cds']=(cds_tmp['TRY'])
cds_tmp['IDR_cds']=(cds_tmp['IDR'])
cds_tmp['PLN_cds']=(cds_tmp['PLN'])
cds_tmp['MYR_cds']=(cds_tmp['MYR'])
cds_tmp['MXN_cds']=(cds_tmp['MXN'])
cds_tmp['KRW_cds']=(cds_tmp['KRW'])
cds_tmp['ZAR_cds']=(cds_tmp['ZAR'])
cds_tmp['ILS_cds']=(cds_tmp['ILS'])
cds_tmp['HUF_cds']=(cds_tmp['HUF'])
cds_tmp['COP_cds']=(cds_tmp['COP'])
cds_tmp['CLP_cds']=(cds_tmp['CLP'])
cds_tmp['BRL_cds']=(cds_tmp['BRL'])
cds_tmp['CNH_cds']=(cds_tmp['CNH'])
cds_tmp['RUB_cds']=(cds_tmp['RUB'])
cds_tmp['PEN_cds']=(cds_tmp['PEN'])

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [13]:
#STEP 12 REVIEW THE DATA AND MAKE BACKUP AND THEN CREADTE FILTER DATA
#Resent index filter date

cds_tmp.head()
cds_tmp1=cds_tmp[cds_tmp.Date >= '2017-01-01']
cds_tmp1=cds_tmp1.reset_index(drop=True)
cds_tmp1.head()
#base = base[base.country != 'Russia']
#base=base.reset_index(drop=True)


#path = os.getcwd()
#print(path)
# /Users/mbp/Documents/my-project/python-snippets/notebook
#print(type(path))
# /Users/mbp/Documents/my-project/python-snippets
#print(table)
#corss latest
#corss average 5 da avg5
#cross average 30  avg30
#cross zscore90 z90
#cross zscore180 z180
#cross zscore360 z360
#cross differnece 5 dif5
#cross differnece 30  dif30
#plt.bar(x,y)
#plt.show()

topics=["EMCDS summary",
        "EMCDS analytics",
        "EMCDS rating",
        "EMCDS pca governance",
        "EMCDS economic cross sectional",
        "EMCDS decision tree",
        "EMCDS regime switch"]

print(topics)        

#CDS RATING FIT 1  model 00001
#CDS PRINICPAL COMPONENET WORLD GOVERNANCE model 00002
#CDS CROSS SECTIONAL ECONOMIC (1) model 00003
#CDS DECISION TREE 3 model 00004
#CDS REGIME SWITHC PLSU CORRELATION (2) model 00005
#Cds summary

# first step , save correclty images
# create pdf pages with multiple images
#cocnatenate images
# savee resutl ina specific folder


#del table_m
#del name_ms
#del smr
#del ms

['EMCDS summary', 'EMCDS analytics', 'EMCDS rating', 'EMCDS pca governance', 'EMCDS economic cross sectional', 'EMCDS decision tree', 'EMCDS regime switch']

In [14]:
#PDF 1st FIRST PART SUMMARY
#Create latest tail 
#e001 = e001.fillna(method='ffill')
table=cds_tmp.tail(1)
table=table.transpose()
table=table.reset_index()
table.columns = ['ticker','value']
table = table.iloc[1:]
table0 = table
print(table)
m = pd.read_csv (r'K:\2020_2431\q\sandbox\summary_table.csv')
m = m[m.symbol != 'ARS']
t=m
#print(m)

      ticker   value
1        ARS  2167.5
2        PHP    67.3
3        CZK    29.9
4        THB    43.3
5        TRY   438.7
..       ...     ...
489  CLP_cds    89.6
490  BRL_cds     207
491  CNH_cds    55.8
492  RUB_cds    88.1
493  PEN_cds    92.1

[493 rows x 2 columns]

In [15]:
#PART 1 SUMARRY CDS 
#create summary table ,  filter all conbiantios fr the table
#ordenar, creart varias tablas y crazar y despues ocnctanerar, despeus gaurdar table como figura
#depsues crear pdf
#matrix with the tickers for one ticker reader


ms=m[['region','country']]    
m0=m[['country','symbol']]
m1=m[['symbol','cds']]
m2=m[['symbol','dif5']]
m3=m[['symbol','dif30']]
m4=m[['symbol','avg5']]
m5=m[['symbol','avg30']]
m6=m[['symbol','std5']]
m7=m[['symbol','std30']]
m8=m[['symbol','mx30']]
m9=m[['symbol','mn30']]
m10=m[['symbol','z90']]
m11=m[['symbol','z180']]
m12=m[['symbol','z360']]
m13=m[['symbol','reg']]

#m10['z90'] = float(m10['z90'].round(3))
#m11['z180'] = float(m11['z180'].round(3))
#m12['z360'] = float(m12['z360'].round(3))


name_ms1='5Y CDS'
name_ms2='Change 5D'
name_ms3='Change 30D'
name_ms4='Avg 5D'
name_ms5='Avg 30D'
name_ms6='Std 5D'
name_ms7='Std 30D'
name_ms8='Max 30D'
name_ms9='Min 30D'
name_ms10='Zscore 3M'
name_ms11='Zscore 6M'
name_ms12='Zscore 12M'
name_ms13='Regional 5Y CDS'


#first latest
table_m=m1
name_ms=name_ms1
smr=pd.merge(table_m, table,  how='left', left_on=['symbol'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
ms = pd.concat([ms,smr], axis=1)
print(ms)

#dif5
table_m=m2
name_ms=name_ms2
table_m.columns=["symbol",'ticker']
print(table_m)
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
print(smr)
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
print(smr)
ms = pd.concat([ms,smr], axis=1)
print(ms)

table_m=m3
name_ms=name_ms3
table_m.columns=["symbol",'ticker']
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
print(smr)
ms = pd.concat([ms,smr], axis=1)
print(ms)

table_m=m4
name_ms=name_ms4
table_m.columns=["symbol",'ticker']
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
ms = pd.concat([ms,smr], axis=1)
print(ms)

table_m=m5
name_ms=name_ms5
table_m.columns=["symbol",'ticker']
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
ms = pd.concat([ms,smr], axis=1)
print(ms)

table_m=m6
name_ms=name_ms6
table_m.columns=["symbol",'ticker']
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
ms = pd.concat([ms,smr], axis=1)
print(ms)


table_m=m7
name_ms=name_ms7
table_m.columns=["symbol",'ticker']
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
ms = pd.concat([ms,smr], axis=1)
print(ms)


table_m=m8
name_ms=name_ms8
table_m.columns=["symbol",'ticker']
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
ms = pd.concat([ms,smr], axis=1)
print(ms)


table_m=m9
name_ms=name_ms9
table_m.columns=["symbol",'ticker']
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
ms = pd.concat([ms,smr], axis=1)
print(ms)


table_m=m10
name_ms=name_ms10
table_m.columns=["symbol",'ticker']
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
ms = pd.concat([ms,smr], axis=1)
print(ms)


table_m=m11
name_ms=name_ms11
table_m.columns=["symbol",'ticker']
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
ms = pd.concat([ms,smr], axis=1)
print(ms)


table_m=m12
name_ms=name_ms12
table_m.columns=["symbol",'ticker']
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
ms = pd.concat([ms,smr], axis=1)
print(ms)


table_m=m13
name_ms=name_ms13
table_m.columns=["symbol",'ticker']
smr=pd.merge(table_m, table,  how='left', left_on=['ticker'], right_on = ['ticker'])
smr.rename(columns={'value':str(name_ms)}, inplace=True)
smr = smr.iloc[: , 2:]
ms = pd.concat([ms,smr], axis=1)
print(ms)
del table

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    region         country ticker 5Y CDS
0    Latam          Brazil    BRL    207
1    Latam          Mexico    MXN  102.5
2    Latam            Peru    PEN   92.1
3    Latam           Chile    CLP   89.6
4    Latam        Colombia    COP    164
5   CEEMEA          Poland    PLN   35.2
6   CEEMEA  Czech Republic    CZK   29.9
7   CEEMEA         Hungary    HUF   49.4
8   CEEMEA          Russia    RUB   88.1
9   CEEMEA    South Africa    ZAR  215.2
10  CEEMEA          Israel    ILS   43.3
11  CEEMEA          Turkey    TRY  438.7
12    Asia           China    CNH   55.8
13    Asia       Indonesia    IDR   94.3
14    Asia        Malaysia    MYR     65
15    Asia           Korea    KRW   21.9
16    Asia        Thailand    THB   43.3
17    Asia     Philippines    PHP   67.3
   symbol    ticker
0     BRL  BRL_dif5
1     MXN  MXN_dif5
2     PEN  PEN_dif5
3     CLP  CLP_dif5
4     COP  COP_dif5
5     PLN  PLN_dif5
6     CZK  CZK_dif5
7     HUF  HUF_dif5
8     RUB  RUB_dif5
9     ZAR  ZAR_dif5
10    ILS  ILS_dif5
11    TRY  TRY_dif5
12    CNH  CNH_dif5
13    IDR  IDR_dif5
14    MYR  MYR_dif5
15    KRW  KRW_dif5
16    THB  THB_dif5
17    PHP  PHP_dif5
   symbol    ticker value
0     BRL  BRL_dif5     1
1     MXN  MXN_dif5   1.5
2     PEN  PEN_dif5 -11.4
3     CLP  CLP_dif5     2
4     COP  COP_dif5  -7.4
5     PLN  PLN_dif5     0
6     CZK  CZK_dif5     0
7     HUF  HUF_dif5     0
8     RUB  RUB_dif5    -2
9     ZAR  ZAR_dif5  -5.4
10    ILS  ILS_dif5     0
11    TRY  TRY_dif5   0.2
12    CNH  CNH_dif5   3.2
13    IDR  IDR_dif5   4.7
14    MYR  MYR_dif5   4.7
15    KRW  KRW_dif5   1.2
16    THB  THB_dif5     0
17    PHP  PHP_dif5   5.5
   Change 5D
0          1
1        1.5
2      -11.4
3          2
4       -7.4
5          0
6          0
7          0
8         -2
9       -5.4
10         0
11       0.2
12       3.2
13       4.7
14       4.7
15       1.2
16         0
17       5.5
    region         country ticker 5Y CDS Change 5D
0    Latam          Brazil    BRL    207         1
1    Latam          Mexico    MXN  102.5       1.5
2    Latam            Peru    PEN   92.1     -11.4
3    Latam           Chile    CLP   89.6         2
4    Latam        Colombia    COP    164      -7.4
5   CEEMEA          Poland    PLN   35.2         0
6   CEEMEA  Czech Republic    CZK   29.9         0
7   CEEMEA         Hungary    HUF   49.4         0
8   CEEMEA          Russia    RUB   88.1        -2
9   CEEMEA    South Africa    ZAR  215.2      -5.4
10  CEEMEA          Israel    ILS   43.3         0
11  CEEMEA          Turkey    TRY  438.7       0.2
12    Asia           China    CNH   55.8       3.2
13    Asia       Indonesia    IDR   94.3       4.7
14    Asia        Malaysia    MYR     65       4.7
15    Asia           Korea    KRW   21.9       1.2
16    Asia        Thailand    THB   43.3         0
17    Asia     Philippines    PHP   67.3       5.5
   Change 30D
0        31.7
1        17.8
2         7.5
3        26.8
4        31.9
5        -3.3
6           0
7           0
8         9.9
9        32.1
10        0.1
11       78.3
12       23.2
13       27.2
14       21.4
15        4.2
16         10
17       23.7
    region         country ticker 5Y CDS Change 5D Change 30D
0    Latam          Brazil    BRL    207         1       31.7
1    Latam          Mexico    MXN  102.5       1.5       17.8
2    Latam            Peru    PEN   92.1     -11.4        7.5
3    Latam           Chile    CLP   89.6         2       26.8
4    Latam        Colombia    COP    164      -7.4       31.9
5   CEEMEA          Poland    PLN   35.2         0       -3.3
6   CEEMEA  Czech Republic    CZK   29.9         0          0
7   CEEMEA         Hungary    HUF   49.4         0          0
8   CEEMEA          Russia    RUB   88.1        -2        9.9
9   CEEMEA    South Africa    ZAR  215.2      -5.4       32.1
10  CEEMEA          Israel    ILS   43.3         0        0.1
11  CEEMEA          Turkey    TRY  438.7       0.2       78.3
12    Asia           China    CNH   55.8       3.2       23.2
13    Asia       Indonesia    IDR   94.3       4.7       27.2
14    Asia        Malaysia    MYR     65       4.7       21.4
15    Asia           Korea    KRW   21.9       1.2        4.2
16    Asia        Thailand    THB   43.3         0         10
17    Asia     Philippines    PHP   67.3       5.5       23.7
    region         country ticker 5Y CDS Change 5D Change 30D Avg 5D
0    Latam          Brazil    BRL    207         1       31.7  205.2
1    Latam          Mexico    MXN  102.5       1.5       17.8  100.7
2    Latam            Peru    PEN   92.1     -11.4        7.5   95.2
3    Latam           Chile    CLP   89.6         2       26.8   87.8
4    Latam        Colombia    COP    164      -7.4       31.9  165.5
5   CEEMEA          Poland    PLN   35.2         0       -3.3   35.2
6   CEEMEA  Czech Republic    CZK   29.9         0          0   29.9
7   CEEMEA         Hungary    HUF   49.4         0          0   49.4
8   CEEMEA          Russia    RUB   88.1        -2        9.9   87.5
9   CEEMEA    South Africa    ZAR  215.2      -5.4       32.1  214.3
10  CEEMEA          Israel    ILS   43.3         0        0.1   43.3
11  CEEMEA          Turkey    TRY  438.7       0.2       78.3  434.6
12    Asia           China    CNH   55.8       3.2       23.2   54.7
13    Asia       Indonesia    IDR   94.3       4.7       27.2   91.3
14    Asia        Malaysia    MYR     65       4.7       21.4   62.2
15    Asia           Korea    KRW   21.9       1.2        4.2   21.6
16    Asia        Thailand    THB   43.3         0         10     43
17    Asia     Philippines    PHP   67.3       5.5       23.7   64.3
    region         country ticker 5Y CDS Change 5D Change 30D Avg 5D Avg 30D
0    Latam          Brazil    BRL    207         1       31.7  205.2   191.7
1    Latam          Mexico    MXN  102.5       1.5       17.8  100.7    92.8
2    Latam            Peru    PEN   92.1     -11.4        7.5   95.2    92.8
3    Latam           Chile    CLP   89.6         2       26.8   87.8    77.3
4    Latam        Colombia    COP    164      -7.4       31.9  165.5   150.3
5   CEEMEA          Poland    PLN   35.2         0       -3.3   35.2    35.6
6   CEEMEA  Czech Republic    CZK   29.9         0          0   29.9    29.9
7   CEEMEA         Hungary    HUF   49.4         0          0   49.4    49.4
8   CEEMEA          Russia    RUB   88.1        -2        9.9   87.5    83.2
9   CEEMEA    South Africa    ZAR  215.2      -5.4       32.1  214.3   198.9
10  CEEMEA          Israel    ILS   43.3         0        0.1   43.3    43.3
11  CEEMEA          Turkey    TRY  438.7       0.2       78.3  434.6   401.3
12    Asia           China    CNH   55.8       3.2       23.2   54.7    42.9
13    Asia       Indonesia    IDR   94.3       4.7       27.2   91.3      78
14    Asia        Malaysia    MYR     65       4.7       21.4   62.2    50.1
15    Asia           Korea    KRW   21.9       1.2        4.2   21.6    19.2
16    Asia        Thailand    THB   43.3         0         10     43    38.3
17    Asia     Philippines    PHP   67.3       5.5       23.7   64.3    50.7
    region         country ticker 5Y CDS Change 5D Change 30D Avg 5D Avg 30D  \
0    Latam          Brazil    BRL    207         1       31.7  205.2   191.7
1    Latam          Mexico    MXN  102.5       1.5       17.8  100.7    92.8
2    Latam            Peru    PEN   92.1     -11.4        7.5   95.2    92.8
3    Latam           Chile    CLP   89.6         2       26.8   87.8    77.3
4    Latam        Colombia    COP    164      -7.4       31.9  165.5   150.3
5   CEEMEA          Poland    PLN   35.2         0       -3.3   35.2    35.6
6   CEEMEA  Czech Republic    CZK   29.9         0          0   29.9    29.9
7   CEEMEA         Hungary    HUF   49.4         0          0   49.4    49.4
8   CEEMEA          Russia    RUB   88.1        -2        9.9   87.5    83.2
9   CEEMEA    South Africa    ZAR  215.2      -5.4       32.1  214.3   198.9
10  CEEMEA          Israel    ILS   43.3         0        0.1   43.3    43.3
11  CEEMEA          Turkey    TRY  438.7       0.2       78.3  434.6   401.3
12    Asia           China    CNH   55.8       3.2       23.2   54.7    42.9
13    Asia       Indonesia    IDR   94.3       4.7       27.2   91.3      78
14    Asia        Malaysia    MYR     65       4.7       21.4   62.2    50.1
15    Asia           Korea    KRW   21.9       1.2        4.2   21.6    19.2
16    Asia        Thailand    THB   43.3         0         10     43    38.3
17    Asia     Philippines    PHP   67.3       5.5       23.7   64.3    50.7

   Std 5D
0     2.7
1     1.9
2     1.9
3       2
4     1.7
5       0
6       0
7       0
8     1.9
9     3.2
10      0
11      6
12      4
13    4.6
14    3.7
15    0.9
16    1.3
17    3.8
    region         country ticker 5Y CDS Change 5D Change 30D Avg 5D Avg 30D  \
0    Latam          Brazil    BRL    207         1       31.7  205.2   191.7
1    Latam          Mexico    MXN  102.5       1.5       17.8  100.7    92.8
2    Latam            Peru    PEN   92.1     -11.4        7.5   95.2    92.8
3    Latam           Chile    CLP   89.6         2       26.8   87.8    77.3
4    Latam        Colombia    COP    164      -7.4       31.9  165.5   150.3
5   CEEMEA          Poland    PLN   35.2         0       -3.3   35.2    35.6
6   CEEMEA  Czech Republic    CZK   29.9         0          0   29.9    29.9
7   CEEMEA         Hungary    HUF   49.4         0          0   49.4    49.4
8   CEEMEA          Russia    RUB   88.1        -2        9.9   87.5    83.2
9   CEEMEA    South Africa    ZAR  215.2      -5.4       32.1  214.3   198.9
10  CEEMEA          Israel    ILS   43.3         0        0.1   43.3    43.3
11  CEEMEA          Turkey    TRY  438.7       0.2       78.3  434.6   401.3
12    Asia           China    CNH   55.8       3.2       23.2   54.7    42.9
13    Asia       Indonesia    IDR   94.3       4.7       27.2   91.3      78
14    Asia        Malaysia    MYR     65       4.7       21.4   62.2    50.1
15    Asia           Korea    KRW   21.9       1.2        4.2   21.6    19.2
16    Asia        Thailand    THB   43.3         0         10     43    38.3
17    Asia     Philippines    PHP   67.3       5.5       23.7   64.3    50.7

   Std 5D Std 30D
0     2.7    13.2
1     1.9     8.2
2     1.9     8.1
3       2    10.4
4     1.7    16.3
5       0     1.1
6       0       0
7       0       0
8     1.9     5.6
9     3.2    14.7
10      0       0
11      6    31.2
12      4     8.6
13    4.6     9.7
14    3.7     7.5
15    0.9     1.5
16    1.3     4.1
17    3.8     8.2
    region         country ticker 5Y CDS Change 5D Change 30D Avg 5D Avg 30D  \
0    Latam          Brazil    BRL    207         1       31.7  205.2   191.7
1    Latam          Mexico    MXN  102.5       1.5       17.8  100.7    92.8
2    Latam            Peru    PEN   92.1     -11.4        7.5   95.2    92.8
3    Latam           Chile    CLP   89.6         2       26.8   87.8    77.3
4    Latam        Colombia    COP    164      -7.4       31.9  165.5   150.3
5   CEEMEA          Poland    PLN   35.2         0       -3.3   35.2    35.6
6   CEEMEA  Czech Republic    CZK   29.9         0          0   29.9    29.9
7   CEEMEA         Hungary    HUF   49.4         0          0   49.4    49.4
8   CEEMEA          Russia    RUB   88.1        -2        9.9   87.5    83.2
9   CEEMEA    South Africa    ZAR  215.2      -5.4       32.1  214.3   198.9
10  CEEMEA          Israel    ILS   43.3         0        0.1   43.3    43.3
11  CEEMEA          Turkey    TRY  438.7       0.2       78.3  434.6   401.3
12    Asia           China    CNH   55.8       3.2       23.2   54.7    42.9
13    Asia       Indonesia    IDR   94.3       4.7       27.2   91.3      78
14    Asia        Malaysia    MYR     65       4.7       21.4   62.2    50.1
15    Asia           Korea    KRW   21.9       1.2        4.2   21.6    19.2
16    Asia        Thailand    THB   43.3         0         10     43    38.3
17    Asia     Philippines    PHP   67.3       5.5       23.7   64.3    50.7

   Std 5D Std 30D Max 30D
0     2.7    13.2   208.9
1     1.9     8.2     103
2     1.9     8.1   106.4
3       2    10.4    90.1
4     1.7    16.3   174.8
5       0     1.1    38.5
6       0       0      30
7       0       0    49.4
8     1.9     5.6    91.1
9     3.2    14.7   220.6
10      0       0    43.3
11      6    31.2   439.6
12      4     8.6    59.8
13    4.6     9.7    96.1
14    3.7     7.5    65.8
15    0.9     1.5    22.7
16    1.3     4.1    44.8
17    3.8     8.2    67.8
    region         country ticker 5Y CDS Change 5D Change 30D Avg 5D Avg 30D  \
0    Latam          Brazil    BRL    207         1       31.7  205.2   191.7
1    Latam          Mexico    MXN  102.5       1.5       17.8  100.7    92.8
2    Latam            Peru    PEN   92.1     -11.4        7.5   95.2    92.8
3    Latam           Chile    CLP   89.6         2       26.8   87.8    77.3
4    Latam        Colombia    COP    164      -7.4       31.9  165.5   150.3
5   CEEMEA          Poland    PLN   35.2         0       -3.3   35.2    35.6
6   CEEMEA  Czech Republic    CZK   29.9         0          0   29.9    29.9
7   CEEMEA         Hungary    HUF   49.4         0          0   49.4    49.4
8   CEEMEA          Russia    RUB   88.1        -2        9.9   87.5    83.2
9   CEEMEA    South Africa    ZAR  215.2      -5.4       32.1  214.3   198.9
10  CEEMEA          Israel    ILS   43.3         0        0.1   43.3    43.3
11  CEEMEA          Turkey    TRY  438.7       0.2       78.3  434.6   401.3
12    Asia           China    CNH   55.8       3.2       23.2   54.7    42.9
13    Asia       Indonesia    IDR   94.3       4.7       27.2   91.3      78
14    Asia        Malaysia    MYR     65       4.7       21.4   62.2    50.1
15    Asia           Korea    KRW   21.9       1.2        4.2   21.6    19.2
16    Asia        Thailand    THB   43.3         0         10     43    38.3
17    Asia     Philippines    PHP   67.3       5.5       23.7   64.3    50.7

   Std 5D Std 30D Max 30D Min 30D
0     2.7    13.2   208.9   172.9
1     1.9     8.2     103    80.7
2     1.9     8.1   106.4    82.7
3       2    10.4    90.1    63.2
4     1.7    16.3   174.8   130.6
5       0     1.1    38.5    35.2
6       0       0      30    29.9
7       0       0    49.4    49.2
8     1.9     5.6    91.1    75.2
9     3.2    14.7   220.6   178.7
10      0       0    43.3    43.3
11      6    31.2   439.6   360.5
12      4     8.6    59.8      33
13    4.6     9.7    96.1    66.7
14    3.7     7.5    65.8    42.3
15    0.9     1.5    22.7    17.4
16    1.3     4.1    44.8      33
17    3.8     8.2    67.8    42.3
    region         country ticker 5Y CDS Change 5D Change 30D Avg 5D Avg 30D  \
0    Latam          Brazil    BRL    207         1       31.7  205.2   191.7
1    Latam          Mexico    MXN  102.5       1.5       17.8  100.7    92.8
2    Latam            Peru    PEN   92.1     -11.4        7.5   95.2    92.8
3    Latam           Chile    CLP   89.6         2       26.8   87.8    77.3
4    Latam        Colombia    COP    164      -7.4       31.9  165.5   150.3
5   CEEMEA          Poland    PLN   35.2         0       -3.3   35.2    35.6
6   CEEMEA  Czech Republic    CZK   29.9         0          0   29.9    29.9
7   CEEMEA         Hungary    HUF   49.4         0          0   49.4    49.4
8   CEEMEA          Russia    RUB   88.1        -2        9.9   87.5    83.2
9   CEEMEA    South Africa    ZAR  215.2      -5.4       32.1  214.3   198.9
10  CEEMEA          Israel    ILS   43.3         0        0.1   43.3    43.3
11  CEEMEA          Turkey    TRY  438.7       0.2       78.3  434.6   401.3
12    Asia           China    CNH   55.8       3.2       23.2   54.7    42.9
13    Asia       Indonesia    IDR   94.3       4.7       27.2   91.3      78
14    Asia        Malaysia    MYR     65       4.7       21.4   62.2    50.1
15    Asia           Korea    KRW   21.9       1.2        4.2   21.6    19.2
16    Asia        Thailand    THB   43.3         0         10     43    38.3
17    Asia     Philippines    PHP   67.3       5.5       23.7   64.3    50.7

   Std 5D Std 30D Max 30D Min 30D Zscore 3M
0     2.7    13.2   208.9   172.9      2.15
1     1.9     8.2     103    80.7      1.78
2     1.9     8.1   106.4    82.7      0.32
3       2    10.4    90.1    63.2      2.42
4     1.7    16.3   174.8   130.6       1.8
5       0     1.1    38.5    35.2     -1.62
6       0       0      30    29.9     -0.87
7       0       0    49.4    49.2      0.15
8     1.9     5.6    91.1    75.2      0.85
9     3.2    14.7   220.6   178.7      1.83
10      0       0    43.3    43.3      0.71
11      6    31.2   439.6   360.5      2.55
12      4     8.6    59.8      33      3.09
13    4.6     9.7    96.1    66.7      2.97
14    3.7     7.5    65.8    42.3      3.52
15    0.9     1.5    22.7    17.4      3.76
16    1.3     4.1    44.8      33      1.91
17    3.8     8.2    67.8    42.3      3.77
    region         country ticker 5Y CDS Change 5D Change 30D Avg 5D Avg 30D  \
0    Latam          Brazil    BRL    207         1       31.7  205.2   191.7
1    Latam          Mexico    MXN  102.5       1.5       17.8  100.7    92.8
2    Latam            Peru    PEN   92.1     -11.4        7.5   95.2    92.8
3    Latam           Chile    CLP   89.6         2       26.8   87.8    77.3
4    Latam        Colombia    COP    164      -7.4       31.9  165.5   150.3
5   CEEMEA          Poland    PLN   35.2         0       -3.3   35.2    35.6
6   CEEMEA  Czech Republic    CZK   29.9         0          0   29.9    29.9
7   CEEMEA         Hungary    HUF   49.4         0          0   49.4    49.4
8   CEEMEA          Russia    RUB   88.1        -2        9.9   87.5    83.2
9   CEEMEA    South Africa    ZAR  215.2      -5.4       32.1  214.3   198.9
10  CEEMEA          Israel    ILS   43.3         0        0.1   43.3    43.3
11  CEEMEA          Turkey    TRY  438.7       0.2       78.3  434.6   401.3
12    Asia           China    CNH   55.8       3.2       23.2   54.7    42.9
13    Asia       Indonesia    IDR   94.3       4.7       27.2   91.3      78
14    Asia        Malaysia    MYR     65       4.7       21.4   62.2    50.1
15    Asia           Korea    KRW   21.9       1.2        4.2   21.6    19.2
16    Asia        Thailand    THB   43.3         0         10     43    38.3
17    Asia     Philippines    PHP   67.3       5.5       23.7   64.3    50.7

   Std 5D Std 30D Max 30D Min 30D Zscore 3M Zscore 6M
0     2.7    13.2   208.9   172.9      2.15       1.3
1     1.9     8.2     103    80.7      1.78      0.95
2     1.9     8.1   106.4    82.7      0.32      0.63
3       2    10.4    90.1    63.2      2.42      2.66
4     1.7    16.3   174.8   130.6       1.8      1.91
5       0     1.1    38.5    35.2     -1.62        -1
6       0       0      30    29.9     -0.87     -0.76
7       0       0    49.4    49.2      0.15     -0.57
8     1.9     5.6    91.1    75.2      0.85     -0.31
9     3.2    14.7   220.6   178.7      1.83      0.77
10      0       0    43.3    43.3      0.71      0.56
11      6    31.2   439.6   360.5      2.55      1.26
12      4     8.6    59.8      33      3.09      3.71
13    4.6     9.7    96.1    66.7      2.97      2.86
14    3.7     7.5    65.8    42.3      3.52      3.99
15    0.9     1.5    22.7    17.4      3.76      1.07
16    1.3     4.1    44.8      33      1.91      1.81
17    3.8     8.2    67.8    42.3      3.77      4.33
    region         country ticker 5Y CDS Change 5D Change 30D Avg 5D Avg 30D  \
0    Latam          Brazil    BRL    207         1       31.7  205.2   191.7
1    Latam          Mexico    MXN  102.5       1.5       17.8  100.7    92.8
2    Latam            Peru    PEN   92.1     -11.4        7.5   95.2    92.8
3    Latam           Chile    CLP   89.6         2       26.8   87.8    77.3
4    Latam        Colombia    COP    164      -7.4       31.9  165.5   150.3
5   CEEMEA          Poland    PLN   35.2         0       -3.3   35.2    35.6

17    3.8     8.2    67.8    42.3      3.77      4.33       2.32
    region         country ticker 5Y CDS Change 5D Change 30D Avg 5D Avg 30D  \
0    Latam          Brazil    BRL    207         1       31.7  205.2   191.7
1    Latam          Mexico    MXN  102.5       1.5       17.8  100.7    92.8
2    Latam            Peru    PEN   92.1     -11.4        7.5   95.2    92.8
3    Latam           Chile    CLP   89.6         2       26.8   87.8    77.3
4    Latam        Colombia    COP    164      -7.4       31.9  165.5   150.3
5   CEEMEA          Poland    PLN   35.2         0       -3.3   35.2    35.6
6   CEEMEA  Czech Republic    CZK   29.9         0          0   29.9    29.9
7   CEEMEA         Hungary    HUF   49.4         0          0   49.4    49.4
8   CEEMEA          Russia    RUB   88.1        -2        9.9   87.5    83.2
9   CEEMEA    South Africa    ZAR  215.2      -5.4       32.1  214.3   198.9
10  CEEMEA          Israel    ILS   43.3         0        0.1   43.3    43.3
11  CEEMEA          Turkey    TRY  438.7       0.2       78.3  434.6   401.3
12    Asia           China    CNH   55.8       3.2       23.2   54.7    42.9
13    Asia       Indonesia    IDR   94.3       4.7       27.2   91.3      78
14    Asia        Malaysia    MYR     65       4.7       21.4   62.2    50.1
15    Asia           Korea    KRW   21.9       1.2        4.2   21.6    19.2
16    Asia        Thailand    THB   43.3         0         10     43    38.3
17    Asia     Philippines    PHP   67.3       5.5       23.7   64.3    50.7

   Std 5D Std 30D Max 30D Min 30D Zscore 3M Zscore 6M Zscore 12M  \
0     2.7    13.2   208.9   172.9      2.15       1.3       0.43
1     1.9     8.2     103    80.7      1.78      0.95      -0.24
2     1.9     8.1   106.4    82.7      0.32      0.63       1.07
3       2    10.4    90.1    63.2      2.42      2.66       2.31
4     1.7    16.3   174.8   130.6       1.8      1.91       1.74
5       0     1.1    38.5    35.2     -1.62        -1      -1.48
6       0       0      30    29.9     -0.87     -0.76         -1
7       0       0    49.4    49.2      0.15     -0.57      -0.94
8     1.9     5.6    91.1    75.2      0.85     -0.31      -0.49
9     3.2    14.7   220.6   178.7      1.83      0.77      -0.46
10      0       0    43.3    43.3      0.71      0.56      -0.79
11      6    31.2   439.6   360.5      2.55      1.26       0.23
12      4     8.6    59.8      33      3.09      3.71       2.69
13    4.6     9.7    96.1    66.7      2.97      2.86        0.3
14    3.7     7.5    65.8    42.3      3.52      3.99       1.48
15    0.9     1.5    22.7    17.4      3.76      1.07      -0.07
16    1.3     4.1    44.8      33      1.91      1.81        0.8
17    3.8     8.2    67.8    42.3      3.77      4.33       2.32

   Regional 5Y CDS
0              112
1            138.2
2            140.8
3            141.4
4            122.8
5            144.1
6              145
7            141.7
8            135.3
9            114.1
10           142.8
11            76.8
12            58.4
13            50.7
14            56.5
15            65.1
16            60.9
17            56.1

In [16]:
######parameter
parameter_sum1 = 14
parameter_sum2 = 4.8
parameter_fontsize = 9
parameter_t_fontsize = 20
parameter_f_fontsize = 10

today0 = str(date.today())
print("Complete")

Complete

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [17]:
#this from pandas.plotting import table
#import matplotlib.pyplot as plt

#import pandas as pd
#import matplotlib.pylab as plt
from pandas.plotting import table

#PART 1 SUMARRY CDS 
os.chdir('K:/2020_2431/q/cds_report/images/tc/report')
print(os.getcwd())

final_location_first = ("K:\\2020_2431\\q\\cds_report\\images\\tc\\report_f\\")
final_location_last = '.pdf'

#file location
location_first= ("K:\\2020_2431\\q\\cds_report\\images\\tc\\")
today = str(date.today())+"_"
location_last = '_fig.pdf'

#title_graph="EM CDS - Rating Fit Model "
label="EMCDS_Summary"
dateTimeObj = str(datetime.now())
print(dateTimeObj)
location=location_first+today+label+location_last
#location=location_first+label+dateTimeObj+location_last
print(location)

ms = pd.DataFrame(ms)


# set fig size
fig, ax = plt.subplots(figsize=(parameter_sum1, parameter_sum2)) 
# no axes
ax.xaxis.set_visible(False)  
ax.yaxis.set_visible(False)  
# no frame
ax.set_frame_on(False)  
# plot table
tab = table(ax, ms, loc='center')  
# set font manually
tab.auto_set_font_size(False)
tab.set_fontsize(parameter_fontsize) 
plt.title("EM CDS - EMERGING MARKETS SOV 5Y CDS: SUMMARY ", 
          size=parameter_t_fontsize,
          loc='center',
          weight='bold',
          color='darkblue')           
#plt.xlabel("TODAY DATE TIME", size=20)
plt.figtext(0.95, 0.05, str(today0),
            horizontalalignment='right',
            size=parameter_f_fontsize,
            weight='light', color='black')
plt.tight_layout()
# save the result
plt.savefig(location)
plt.savefig("001_technical.pdf")
plt.savefig(final_location_first+ "001_technical" +final_location_last )


#K:\2020_2431\q\cds_report\images\tc
#K:\\2020_2431\\q\\cds_report\\images\\tc\\table.pdf'

#https://stackoverflow.com/questions/44751045/save-pandas-table-filled-with-strings-as-png
print("Complete")

K:\2020_2431\q\cds_report\images\tc\report
2021-10-14 12:29:55.758459
K:\2020_2431\q\cds_report\images\tc\2021-10-14_EMCDS_Summary_fig.pdf
Complete

In [18]:
######parameters comaprison tables
parameter1 = 15
parameter2 = 10
parameter3 = 11
parameter4 = 10
parameter_graph_label = 15
print("Complete")

Complete

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [19]:
#part 2

###part 2 proces create summary comparison tables for the techncial creprot
os.chdir('K:/2020_2431/q/cds_report/images/tc/report')
print(os.getcwd())

#be careful run again table  dat
#file location and albels
location_first= ("K:\\2020_2431\\q\\cds_report\\images\\tc\\")
today = str(date.today())
location_last = '_fig.pdf'
source="Source: EGM-LDN"
#title_graph="EM CDS - Rating Fit Model "
label="Sov CDS 5Y Spread"
dateTimeObj = str(datetime.now())
print(dateTimeObj)
location=location_first+today+label+location_last
#location=location_first+label+dateTimeObj+location_last
print(location)
y="EM Sov CDS 5Y Spread"
x_label=today+" "+source


fig_name="fig_"
number=0


############cds

t0=t[['country','symbol','cds']]
variable= "Today Market data"
y_label= variable +" - " +y
title_text= label+" "+ variable +" "+today
location=location_first+today+label+variable+location_last
#list=['BRL_reg','CLP_reg','COP_reg','PEN_reg','MXN_reg','CZK_reg','HUF_reg','RUB_reg','ZAR_reg','PLN_reg','ILS_reg','TRY_reg', 'PHP_reg','THB_reg','CNH_reg','KRW_reg','MYR_reg','IDR_reg']
#list = DataFrame (list,columns=['ticker'])

graph0 = pd.merge(t0, table0,  how='left', left_on=['cds'], right_on = ['ticker'])
graph0=graph0[['country','value']]
graph0 = graph0.sort_values(['value'], ascending=[False])
print(graph0)
#fig,ax = plt.subplots(figsize=(15,6))
#g1.plot(kind='line',ax=ax,color=['blue'])
#plt.bar(graph0.ticker,graph0.value)
#plt.savefig(location)

#namefigure
number=number+1
number_t=str(int(number))
fig_name_t=fig_name+number_t+".jpg"
print(fig_name_t)

#large and height
plt.figure(figsize=(parameter1,parameter2))
sns.set_style('whitegrid')
splot=sns.barplot(x="country", y="value", data=graph0, palette=["blue"])
plt.ylabel(str(y_label), size=parameter3)
plt.xlabel(str(x_label), size=parameter3)
plt.title(str(title_text), size=20)
plt.tick_params(labelsize=parameter4)
for p in splot.patches:
    splot.annotate(format(p.get_height(), '.0f'), 
                   (p.get_x() + p.get_width() / 2., p.get_height()), 
                   ha = 'center', va = 'center', 
                   size=parameter_graph_label,
                   weight='bold',
                   xytext = (0, -12), 
                   textcoords = 'offset points')
plt.savefig(location, bbox_inches='tight')
plt.savefig(str(fig_name_t), bbox_inches='tight')
#fig1=plt.figure()
#fig1 = plt.plot()
plt.show()
plt.close()


############avg5##################################################################


t0=t[['country','symbol','avg5']]
variable= "Average 5D"
y_label= variable +" - " +y
title_text= label+" "+ variable +" "+today
location=location_first+today+label+variable+location_last
#list=['BRL_reg','CLP_reg','COP_reg','PEN_reg','MXN_reg','CZK_reg','HUF_reg','RUB_reg','ZAR_reg','PLN_reg','ILS_reg','TRY_reg', 'PHP_reg','THB_reg','CNH_reg','KRW_reg','MYR_reg','IDR_reg']
#list = DataFrame (list,columns=['ticker'])
###update
graph0 = pd.merge(t0, table0,  how='left', left_on=['avg5'], right_on = ['ticker'])
graph0=graph0[['country','value']]
graph0 = graph0.sort_values(['value'], ascending=[False])
print(graph0)
#fig,ax = plt.subplots(figsize=(15,6))
#g1.plot(kind='line',ax=ax,color=['blue'])
#plt.bar(graph0.ticker,graph0.value)
#plt.savefig(location)

#namefigure
number=number+1
number_t=str(int(number))
fig_name_t=fig_name+number_t+".jpg"
print(fig_name_t)

#large and height
plt.figure(figsize=(parameter1,parameter2))
sns.set_style('whitegrid')
splot=sns.barplot(x="country", y="value", data=graph0, palette=["blue"])
plt.ylabel(str(y_label), size=parameter3)
plt.xlabel(str(x_label), size=parameter3)
plt.title(str(title_text), size=20)
plt.tick_params(labelsize=parameter4)
for p in splot.patches:
    splot.annotate(format(p.get_height(), '.0f'), 
                   (p.get_x() + p.get_width() / 2., p.get_height()), 
                   ha = 'center', va = 'center', 
                   size=parameter_graph_label,
                   weight='bold',
                   xytext = (0, -12), 
                   textcoords = 'offset points')
plt.savefig(location, bbox_inches='tight')
plt.savefig(str(fig_name_t), bbox_inches='tight')
plt.show()



##########
############avg30################################################
t0=t[['country','symbol','avg30']]
#####updt
variable= "Average 30D"
y_label= variable +" - " +y
title_text= label+" "+ variable +" "+today
location=location_first+today+label+variable+location_last
#list=['BRL_reg','CLP_reg','COP_reg','PEN_reg','MXN_reg','CZK_reg','HUF_reg','RUB_reg','ZAR_reg','PLN_reg','ILS_reg','TRY_reg', 'PHP_reg','THB_reg','CNH_reg','KRW_reg','MYR_reg','IDR_reg']
#list = DataFrame (list,columns=['ticker'])
###update#####updt
graph0 = pd.merge(t0, table0,  how='left', left_on=['avg30'], right_on = ['ticker'])
graph0=graph0[['country','value']]
graph0 = graph0.sort_values(['value'], ascending=[False])
print(graph0)
#fig,ax = plt.subplots(figsize=(15,6))
#g1.plot(kind='line',ax=ax,color=['blue'])
#plt.bar(graph0.ticker,graph0.value)
#plt.savefig(location)

#namefigure
number=number+1
number_t=str(int(number))
fig_name_t=fig_name+number_t+".jpg"
print(fig_name_t)

#large and height
plt.figure(figsize=(parameter1,parameter2))
sns.set_style('whitegrid')
splot=sns.barplot(x="country", y="value", data=graph0, palette=["blue"])
plt.ylabel(str(y_label), size=parameter3)
plt.xlabel(str(x_label), size=parameter3)
plt.title(str(title_text), size=20)
plt.tick_params(labelsize=parameter4)
for p in splot.patches:
    splot.annotate(format(p.get_height(), '.0f'), 
                   (p.get_x() + p.get_width() / 2., p.get_height()), 
                   ha = 'center', va = 'center', 
                   size=parameter_graph_label,
                   weight='bold',
                   xytext = (0, -12), 
                   textcoords = 'offset points')
plt.savefig(location, bbox_inches='tight')
plt.savefig(str(fig_name_t), bbox_inches='tight')
plt.show()





##########
############dif5  #######################################################################
t0=t[['country','symbol','dif5']]
#####updt
variable= "Dif 5D"
y_label= variable +" - " +y
title_text= label+" "+ variable +" "+today
location=location_first+today+label+variable+location_last
#list=['BRL_reg','CLP_reg','COP_reg','PEN_reg','MXN_reg','CZK_reg','HUF_reg','RUB_reg','ZAR_reg','PLN_reg','ILS_reg','TRY_reg', 'PHP_reg','THB_reg','CNH_reg','KRW_reg','MYR_reg','IDR_reg']
#list = DataFrame (list,columns=['ticker'])
###update#####updt
graph0 = pd.merge(t0, table0,  how='left', left_on=['dif5'], right_on = ['ticker'])
graph0=graph0[['country','value']]
graph0 = graph0.sort_values(['value'], ascending=[False])
print(graph0)
#fig,ax = plt.subplots(figsize=(15,6))
#g1.plot(kind='line',ax=ax,color=['blue'])
#plt.bar(graph0.ticker,graph0.value)
#plt.savefig(location)

#namefigure
number=number+1
number_t=str(int(number))
fig_name_t=fig_name+number_t+".jpg"
print(fig_name_t)

#large and height
plt.figure(figsize=(parameter1,parameter2))
sns.set_style('whitegrid')
splot=sns.barplot(x="country", y="value", data=graph0, palette=["orange"])
plt.ylabel(str(y_label), size=parameter3)
plt.xlabel(str(x_label), size=parameter3)
plt.title(str(title_text), size=20)
plt.tick_params(labelsize=parameter4)
for p in splot.patches:
    splot.annotate(format(p.get_height(), '.0f'), 
                   (p.get_x() + p.get_width() / 2., p.get_height()), 
                   ha = 'center', va = 'center', 
                   size=parameter_graph_label,
                   weight='bold',
                   xytext = (0, -12), 
                   textcoords = 'offset points')
plt.savefig(location, bbox_inches='tight')
plt.savefig(str(fig_name_t), bbox_inches='tight')
plt.show()



############dif30 #############################################################################
t0=t[['country','symbol','dif30']]
#####updt
variable= "Dif 30D"
y_label= variable +" - " +y
title_text= label+" "+ variable +" "+today
location=location_first+today+label+variable+location_last
#list=['BRL_reg','CLP_reg','COP_reg','PEN_reg','MXN_reg','CZK_reg','HUF_reg','RUB_reg','ZAR_reg','PLN_reg','ILS_reg','TRY_reg', 'PHP_reg','THB_reg','CNH_reg','KRW_reg','MYR_reg','IDR_reg']
#list = DataFrame (list,columns=['ticker'])
###update#####updt
graph0 = pd.merge(t0, table0,  how='left', left_on=['dif30'], right_on = ['ticker'])
graph0=graph0[['country','value']]
graph0 = graph0.sort_values(['value'], ascending=[False])
print(graph0)
#fig,ax = plt.subplots(figsize=(15,6))
#g1.plot(kind='line',ax=ax,color=['blue'])
#plt.bar(graph0.ticker,graph0.value)
#plt.savefig(location)

#namefigure
number=number+1
number_t=str(int(number))
fig_name_t=fig_name+number_t+".jpg"
print(fig_name_t)

#large and height
plt.figure(figsize=(parameter1,parameter2))
sns.set_style('whitegrid')
splot=sns.barplot(x="country", y="value", data=graph0, palette=["orange"])
plt.ylabel(str(y_label), size=parameter3)
plt.xlabel(str(x_label), size=parameter3)
plt.title(str(title_text), size=20)
plt.tick_params(labelsize=parameter4)
for p in splot.patches:
    splot.annotate(format(p.get_height(), '.0f'), 
                   (p.get_x() + p.get_width() / 2., p.get_height()), 
                   ha = 'center', va = 'center', 
                   size=parameter_graph_label,
                   weight='bold',
                   xytext = (0, -12), 
                   textcoords = 'offset points')
plt.savefig(location, bbox_inches='tight')
plt.savefig(str(fig_name_t), bbox_inches='tight')
plt.show()




############z90 ############################################################
t0=t[['country','symbol','z90']]
#####updt
variable= "Zscore 90D"
y_label= variable +" - " +y
title_text= label+" "+ variable +" "+today
location=location_first+today+label+variable+location_last
#list=['BRL_reg','CLP_reg','COP_reg','PEN_reg','MXN_reg','CZK_reg','HUF_reg','RUB_reg','ZAR_reg','PLN_reg','ILS_reg','TRY_reg', 'PHP_reg','THB_reg','CNH_reg','KRW_reg','MYR_reg','IDR_reg']
#list = DataFrame (list,columns=['ticker'])
###update#####updt
graph0 = pd.merge(t0, table0,  how='left', left_on=['z90'], right_on = ['ticker'])
graph0=graph0[['country','value']]
graph0 = graph0.sort_values(['value'], ascending=[False])
print(graph0)
#fig,ax = plt.subplots(figsize=(15,6))
#g1.plot(kind='line',ax=ax,color=['blue'])
#plt.bar(graph0.ticker,graph0.value)
#plt.savefig(location)

#namefigure
number=number+1
number_t=str(int(number))
fig_name_t=fig_name+number_t+".jpg"
print(fig_name_t)

#large and height
plt.figure(figsize=(parameter1,parameter2))
sns.set_style('whitegrid')
splot=sns.barplot(x="country", y="value", data=graph0, palette=["black"])
plt.ylabel(str(y_label), size=parameter3)
plt.xlabel(str(x_label), size=parameter3)
plt.title(str(title_text), size=20)
plt.tick_params(labelsize=parameter4)
for p in splot.patches:
    splot.annotate(format(p.get_height(), '.0f'), 
                   (p.get_x() + p.get_width() / 2., p.get_height()), 
                   ha = 'center', va = 'center', 
                   size=parameter_graph_label,
                   weight='bold',
                   xytext = (0, -12), 
                   textcoords = 'offset points')
plt.savefig(location, bbox_inches='tight')
plt.savefig(str(fig_name_t), bbox_inches='tight')
plt.show()



############180 ##################################################################
t0=t[['country','symbol','z180']]
#####updt
variable= "Zscore 180D"
y_label= variable +" - " +y
title_text= label+" "+ variable +" "+today
location=location_first+today+label+variable+location_last
#list=['BRL_reg','CLP_reg','COP_reg','PEN_reg','MXN_reg','CZK_reg','HUF_reg','RUB_reg','ZAR_reg','PLN_reg','ILS_reg','TRY_reg', 'PHP_reg','THB_reg','CNH_reg','KRW_reg','MYR_reg','IDR_reg']
#list = DataFrame (list,columns=['ticker'])
###update#####updt
graph0 = pd.merge(t0, table0,  how='left', left_on=['z180'], right_on = ['ticker'])
graph0=graph0[['country','value']]
graph0 = graph0.sort_values(['value'], ascending=[False])
print(graph0)
#fig,ax = plt.subplots(figsize=(15,6))
#g1.plot(kind='line',ax=ax,color=['blue'])
#plt.bar(graph0.ticker,graph0.value)
#plt.savefig(location)

#namefigure
number=number+1
number_t=str(int(number))
fig_name_t=fig_name+number_t+".jpg"
print(fig_name_t)

#large and height
plt.figure(figsize=(parameter1,parameter2))
sns.set_style('whitegrid')
splot=sns.barplot(x="country", y="value", data=graph0, palette=["black"])
plt.ylabel(str(y_label), size=parameter3)
plt.xlabel(str(x_label), size=parameter3)
plt.title(str(title_text), size=20)
plt.tick_params(labelsize=parameter4)
for p in splot.patches:
    splot.annotate(format(p.get_height(), '.0f'), 
                   (p.get_x() + p.get_width() / 2., p.get_height()), 
                   ha = 'center', va = 'center', 
                   size=parameter_graph_label,
                   weight='bold',
                   xytext = (0, -12), 
                   textcoords = 'offset points')
plt.savefig(location, bbox_inches='tight')
plt.savefig(str(fig_name_t), bbox_inches='tight')
plt.show()



############z360 #####################################################################
t0=t[['country','symbol','z360']]
#####updt
variable= "Zscore 360D"
y_label= variable +" - " +y
title_text= label+" "+ variable +" "+today
location=location_first+today+label+variable+location_last
#list=['BRL_reg','CLP_reg','COP_reg','PEN_reg','MXN_reg','CZK_reg','HUF_reg','RUB_reg','ZAR_reg','PLN_reg','ILS_reg','TRY_reg', 'PHP_reg','THB_reg','CNH_reg','KRW_reg','MYR_reg','IDR_reg']
#list = DataFrame (list,columns=['ticker'])
###update#####updt
graph0 = pd.merge(t0, table0,  how='left', left_on=['z360'], right_on = ['ticker'])
graph0=graph0[['country','value']]
graph0 = graph0.sort_values(['value'], ascending=[False])
print(graph0)
#fig,ax = plt.subplots(figsize=(15,6))
#g1.plot(kind='line',ax=ax,color=['blue'])
#plt.bar(graph0.ticker,graph0.value)
#plt.savefig(location)

#namefigure
number=number+1
number_t=str(int(number))
fig_name_t=fig_name+number_t+".jpg"
print(fig_name_t)

#large and height
plt.figure(figsize=(parameter1,parameter2))
sns.set_style('whitegrid')
splot=sns.barplot(x="country", y="value", data=graph0, palette=["black"])
plt.ylabel(str(y_label), size=parameter3)
plt.xlabel(str(x_label), size=parameter3)
plt.title(str(title_text), size=20)
plt.tick_params(labelsize=parameter4)
for p in splot.patches:
    splot.annotate(format(p.get_height(), '.0f'), 
                   (p.get_x() + p.get_width() / 2., p.get_height()), 
                   ha = 'center', va = 'center', 
                   size=parameter_graph_label,
                   weight='bold',
                   xytext = (0, -12), 
                   textcoords = 'offset points')
plt.savefig(location, bbox_inches='tight')
plt.savefig(str(fig_name_t), bbox_inches='tight')
plt.show()


print("Complete!!!!!")

K:\2020_2431\q\cds_report\images\tc\report
2021-10-14 12:30:02.538650
K:\2020_2431\q\cds_report\images\tc\2021-10-14Sov CDS 5Y Spread_fig.pdf
           country  value
11          Turkey  438.7
9     South Africa  215.2
0           Brazil    207
4         Colombia    164
1           Mexico  102.5
13       Indonesia   94.3
2             Peru   92.1
3            Chile   89.6
8           Russia   88.1
17     Philippines   67.3
14        Malaysia     65
12           China   55.8
7          Hungary   49.4
10          Israel   43.3
16        Thailand   43.3
5           Poland   35.2
6   Czech Republic   29.9
15           Korea   21.9
fig_1.jpg

<ipython-input-19-69389250f01c>:73: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

           country  value
11          Turkey  434.6
9     South Africa  214.3
0           Brazil  205.2
4         Colombia  165.5
1           Mexico  100.7
2             Peru   95.2
13       Indonesia   91.3
3            Chile   87.8
8           Russia   87.5
17     Philippines   64.3
14        Malaysia   62.2
12           China   54.7
7          Hungary   49.4
10          Israel   43.3
16        Thailand     43
5           Poland   35.2
6   Czech Republic   29.9
15           Korea   21.6
fig_2.jpg

<ipython-input-19-69389250f01c>:121: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

           country  value
11          Turkey  401.3
9     South Africa  198.9
0           Brazil  191.7
4         Colombia  150.3
1           Mexico   92.8
2             Peru   92.8
8           Russia   83.2
13       Indonesia     78
3            Chile   77.3
17     Philippines   50.7
14        Malaysia   50.1
7          Hungary   49.4
10          Israel   43.3
12           China   42.9
16        Thailand   38.3
5           Poland   35.6
6   Czech Republic   29.9
15           Korea   19.2
fig_3.jpg

<ipython-input-19-69389250f01c>:169: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

           country value
17     Philippines   5.5
14        Malaysia   4.7
13       Indonesia   4.7
12           China   3.2
3            Chile     2
1           Mexico   1.5
15           Korea   1.2
0           Brazil     1
11          Turkey   0.2
7          Hungary     0
10          Israel     0
6   Czech Republic     0
5           Poland     0
16        Thailand     0
8           Russia    -2
9     South Africa  -5.4
4         Colombia  -7.4
2             Peru -11.4
fig_4.jpg

<ipython-input-19-69389250f01c>:219: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

           country value
11          Turkey  78.3
9     South Africa  32.1
4         Colombia  31.9
0           Brazil  31.7
13       Indonesia  27.2
3            Chile  26.8
17     Philippines  23.7
12           China  23.2
14        Malaysia  21.4
1           Mexico  17.8
16        Thailand    10
8           Russia   9.9
2             Peru   7.5
15           Korea   4.2
10          Israel   0.1
6   Czech Republic     0
7          Hungary     0
5           Poland  -3.3
fig_5.jpg

<ipython-input-19-69389250f01c>:266: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

           country value
17     Philippines  3.77
15           Korea  3.76
14        Malaysia  3.52
12           China  3.09
13       Indonesia  2.97
11          Turkey  2.55
3            Chile  2.42
0           Brazil  2.15
16        Thailand  1.91
9     South Africa  1.83
4         Colombia   1.8
1           Mexico  1.78
8           Russia  0.85
10          Israel  0.71
2             Peru  0.32
7          Hungary  0.15
6   Czech Republic -0.87
5           Poland -1.62
fig_6.jpg

<ipython-input-19-69389250f01c>:314: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

           country value
17     Philippines  4.33
14        Malaysia  3.99
12           China  3.71
13       Indonesia  2.86
3            Chile  2.66
4         Colombia  1.91
16        Thailand  1.81
0           Brazil   1.3
11          Turkey  1.26
15           Korea  1.07
1           Mexico  0.95
9     South Africa  0.77
2             Peru  0.63
10          Israel  0.56
8           Russia -0.31
7          Hungary -0.57
6   Czech Republic -0.76
5           Poland    -1
fig_7.jpg

<ipython-input-19-69389250f01c>:361: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

           country value
12           China  2.69
17     Philippines  2.32
3            Chile  2.31
4         Colombia  1.74
14        Malaysia  1.48
2             Peru  1.07
16        Thailand   0.8
0           Brazil  0.43
13       Indonesia   0.3
11          Turkey  0.23
15           Korea -0.07
1           Mexico -0.24
9     South Africa -0.46
8           Russia -0.49
10          Israel -0.79
7          Hungary -0.94
6   Czech Republic    -1
5           Poland -1.48
fig_8.jpg
Complete!!!!!

<ipython-input-19-69389250f01c>:408: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

In [20]:
#pART 2 CORSSE CITONAL COMPARISON COUNTRY
######cocnatenate aggregate the figure from previos step

os.chdir('K:/2020_2431/q/cds_report/images/tc/report')
print(os.getcwd())

final_location_first = ("K:\\2020_2431\\q\\cds_report\\images\\tc\\report_f\\")
final_location_last = '.pdf'

#######
list_im = ["fig_1.jpg","fig_3.jpg"]
#not consider 5 day averga
#list_im = ["fig_1.jpg","fig_2.jpg","fig_3.jpg"]
imgs    = [ PIL.Image.open(i) for i in list_im ]
# pick the image which is the smallest, and resize the others to match it (can be arbitrary image shape here)
min_shape = sorted( [(np.sum(i.size), i.size ) for i in imgs])[0][1]
imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

    
# for a vertical stacking it is simple: use vstack
imgs_comb = np.vstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )
imgs_comb = PIL.Image.fromarray( imgs_comb)
imgs_comb.save( '002_technical.pdf' )
imgs_comb.save( str(final_location_first+"002_technical"+final_location_last) ) 


########
list_im = ["fig_4.jpg","fig_5.jpg"]
imgs    = [ PIL.Image.open(i) for i in list_im ]
# pick the image which is the smallest, and resize the others to match it (can be arbitrary image shape here)
min_shape = sorted( [(np.sum(i.size), i.size ) for i in imgs])[0][1]
imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

    
# for a vertical stacking it is simple: use vstack
imgs_comb = np.vstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )
imgs_comb = PIL.Image.fromarray( imgs_comb)
imgs_comb.save( '003_technical.pdf' )
imgs_comb.save( str(final_location_first+"003_technical"+final_location_last) ) 

########
#not consider z score 360
#list_im = ["fig_6.jpg","fig_7.jpg","fig_8.jpg"]
list_im = ["fig_6.jpg","fig_7.jpg"]
imgs    = [ PIL.Image.open(i) for i in list_im ]
# pick the image which is the smallest, and resize the others to match it (can be arbitrary image shape here)
min_shape = sorted( [(np.sum(i.size), i.size ) for i in imgs])[0][1]
imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

    
# for a vertical stacking it is simple: use vstack
imgs_comb = np.vstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )
imgs_comb = PIL.Image.fromarray( imgs_comb)
imgs_comb.save( '004_technical.pdf' )
imgs_comb.save( str(final_location_first+"004_technical"+final_location_last) ) 
print("Complete!!!")

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
<ipython-input-20-6c1134814582>:17: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

K:\2020_2431\q\cds_report\images\tc\report
Complete!!!

In [21]:
#part 3 PDF all countries   
#BUT BEFORE CREEATE BACKUP OF DATA

#PLOT, NORMAL x2,, 1rolling average and complete rolling avera x3 x2
#PLOTZSCORES x3 x2
#BASE YEAR 2010
#COMPRAE CORSS PLOT HIGHEST CHANGES
#PLOT CROSS HIGES ZSCOERRE
#cds_tmp.columns


df=cds_tmp
df1=cds_tmp1
print("Complete")

Complete

In [22]:
#part 3 PDF all countries  
#generates all the charts


###proces create summary comparison tables for the techncial creprot
os.chdir('K:/2020_2431/q/cds_report/images/tc/report_c')
print(os.getcwd())

#file location
location_first= ("K:\\2020_2431\\q\\cds_report\\images\\tc\\")
today = str(date.today())+"_"
location_last = '_fig.pdf'


#title_graph="EM CDS - Rating Fit Model "
x_label=" EM CDS "
dateTimeObj = str(datetime.now())
print(dateTimeObj)
title0="EMCDS // Sov CDS "
y_label="Sov CDS 5y"


#country=
lst = ['BRL','COP','MXN','CLP','PEN','CZK','HUF','PLN','RUB','ILS','ZAR','TRY','IDR','THB','MYR','KRW','PHP']



#namefigure

parameter1 =15
parameter2 =7
parameter3=10
parameter4=22
fig_name="fig_c_"
number=0


#number=number+1
#number_t=str(int(number))
#fig_name_t=fig_name+country+number_t+".jpg"
#print(fig_name_t)
#plt.savefig(str(fig_name_t), bbox_inches='tight')


for x in range(len(lst)): 

    country=str(lst[x])  
    
    #cds
    name=country
    cds_series=country+"_cds"
    title=y_label+" "+country
    location=location_first+today+cds_series+location_last
    print(cds_series)
    g=df.filter(regex=str(cds_series))
    g=pd.concat([df[['Date']],g], axis = 1)
    g1 = g.set_index('Date') # setting "Years" as index
    g1.head()
    #plot
    fig,ax = plt.subplots(figsize=(parameter1,parameter2))
    g1.plot(kind='line',ax=ax,color=['blue'])
    plt.ylabel(str(y_label), size=parameter3)
    plt.xlabel(str(x_label), size=parameter3)
    plt.title(str(title), size=parameter4)
    plt.grid(axis='both', alpha=.3)
    plt.savefig(location, bbox_inches='tight')
    number=number+1
    number_t=str(int(number))
    fig_name_t=fig_name+country+number_t+".jpg"
    print(fig_name_t)
    plt.savefig(str(fig_name_t), bbox_inches='tight')


    #cds+avg30
    name=country
    cds_series1=country+"_cds"
    cds_series3=country+"_avg30"
    title=y_label+" "+cds_series3
    location=location_first+today+cds_series3+location_last
    print(cds_series)
    g_01=df.filter(regex=str(cds_series1))
    g_03=df.filter(regex=str(cds_series3))
    g=pd.concat([df[['Date']],g_01,g_03], axis = 1)
    g1 = g.set_index('Date') # setting "Years" as index
    g1.head()
    #plot
    fig,ax = plt.subplots(figsize=(parameter1,parameter2))
    g1.plot(kind='line',ax=ax,color=['blue',"orange"])
    plt.ylabel(str(y_label), size=parameter3)
    plt.xlabel(str(x_label), size=parameter3)
    plt.title(str(title), size=parameter4)
    plt.grid(axis='both', alpha=.3)
    plt.savefig(location, bbox_inches='tight')
    number=number+1
    number_t=str(int(number))
    fig_name_t=fig_name+country+number_t+".jpg"
    print(fig_name_t)
    plt.savefig(str(fig_name_t), bbox_inches='tight')
    
    
    
    #avgsssss
    name=country
    cds_series=country+"_avg"
    cds_series1=country+"_avg5"
    cds_series2=country+"_avg15"
    cds_series3=country+"_avg30"
    cds_series4=country+"_avg90"
    title=y_label+" "+country
    location=location_first+today+cds_series+location_last
    print(cds_series)
    g_01=df.filter(regex=str(cds_series1))
    g_02=df.filter(regex=str(cds_series2))
    g_03=df.filter(regex=str(cds_series3))
    g_04=df.filter(regex=str(cds_series4))
    g=pd.concat([df[['Date']],g_01,g_02,g_03,g_04], axis = 1)
    g1 = g.set_index('Date') # setting "Years" as index
    g1.head()
    #plot
    fig,ax = plt.subplots(figsize=(parameter1,parameter2))
    g1.plot(kind='line',ax=ax,color=['blue',"yellow","orange","red"])
    plt.ylabel(str(y_label), size=parameter3)
    plt.xlabel(str(x_label), size=parameter3)
    plt.title(str(title), size=parameter4)
    plt.grid(axis='both', alpha=.3)
    plt.savefig(location, bbox_inches='tight')
    number=number+1
    number_t=str(int(number))
    fig_name_t=fig_name+country+number_t+".jpg"
    print(fig_name_t)
    plt.savefig(str(fig_name_t), bbox_inches='tight')
    
    
    
    #zscore
    name=country
    cds_series=country+"_zscore180"
    cds_series2=country+"_z180"
    title=y_label+" "+cds_series
    location=location_first+today+cds_series+location_last
    print(cds_series)
    g_02=df.filter(regex=str(cds_series2))
    g=pd.concat([df[['Date']],g_02], axis = 1)
    g1 = g.set_index('Date') # setting "Years" as index
    g1.head()
    #plot
    fig,ax = plt.subplots(figsize=(parameter1,parameter2))
    g1.plot(kind='line',ax=ax,color=['blue'])
    plt.ylabel(str(y_label), size=parameter3)
    plt.xlabel(str(x_label), size=parameter3)
    plt.title(str(title), size=parameter4)
    plt.grid(axis='both', alpha=.3)
    plt.axhline(0, color='black', lw=1, alpha=0.6)
    plt.savefig(location, bbox_inches='tight')
    number=number+1
    number_t=str(int(number))
    fig_name_t=fig_name+country+number_t+".jpg"
    print(fig_name_t)
    plt.savefig(str(fig_name_t), bbox_inches='tight')
    

    #all zscores
    name=country
    cds_series=country+"_zscore"
    cds_series1=country+"_z90"
    cds_series2=country+"_z180"
    cds_series3=country+"_z360"
    title=y_label+" "+cds_series
    location=location_first+today+cds_series+location_last
    print(cds_series)
    g_01=df.filter(regex=str(cds_series1))
    g_02=df.filter(regex=str(cds_series2))
    g_03=df.filter(regex=str(cds_series3))
    g=pd.concat([df[['Date']],g_01,g_02,g_03], axis = 1)
    g1 = g.set_index('Date') # setting "Years" as index
    g1.head()
    #plot
    fig,ax = plt.subplots(figsize=(parameter1,parameter2))
    g1.plot(kind='line',ax=ax,color=['blue',"gray",'black'])
    plt.ylabel(str(y_label), size=parameter3)
    plt.xlabel(str(x_label), size=parameter3)
    plt.title(str(title), size=parameter4)
    plt.grid(axis='both', alpha=.3)
    plt.axhline(0, color='black', lw=1, alpha=0.6)
    plt.savefig(location, bbox_inches='tight')
    number=number+1
    number_t=str(int(number))
    fig_name_t=fig_name+country+number_t+".jpg"
    print(fig_name_t)
    plt.savefig(str(fig_name_t), bbox_inches='tight')
    number=0

    
#reset number    
number=0
print("Complete!!!")

K:\2020_2431\q\cds_report\images\tc\report_c
2021-10-14 12:30:14.199168
BRL_cds
fig_c_BRL1.jpg
BRL_cds
fig_c_BRL2.jpg
BRL_avg
fig_c_BRL3.jpg
BRL_zscore180
fig_c_BRL4.jpg
BRL_zscore
fig_c_BRL5.jpg
COP_cds
fig_c_COP1.jpg
COP_cds
fig_c_COP2.jpg
COP_avg
fig_c_COP3.jpg
COP_zscore180
fig_c_COP4.jpg
COP_zscore
fig_c_COP5.jpg
MXN_cds
fig_c_MXN1.jpg
MXN_cds
fig_c_MXN2.jpg
MXN_avg

<ipython-input-22-3ed205088dbc>:120: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig,ax = plt.subplots(figsize=(parameter1,parameter2))

fig_c_MXN3.jpg
MXN_zscore180
fig_c_MXN4.jpg
MXN_zscore
fig_c_MXN5.jpg
CLP_cds
fig_c_CLP1.jpg
CLP_cds
fig_c_CLP2.jpg
CLP_avg
fig_c_CLP3.jpg
CLP_zscore180
fig_c_CLP4.jpg
CLP_zscore
fig_c_CLP5.jpg
PEN_cds
fig_c_PEN1.jpg
PEN_cds
fig_c_PEN2.jpg
PEN_avg
fig_c_PEN3.jpg
PEN_zscore180
fig_c_PEN4.jpg
PEN_zscore
fig_c_PEN5.jpg
CZK_cds
fig_c_CZK1.jpg
CZK_cds
fig_c_CZK2.jpg
CZK_avg
fig_c_CZK3.jpg
CZK_zscore180
fig_c_CZK4.jpg
CZK_zscore
fig_c_CZK5.jpg
HUF_cds
fig_c_HUF1.jpg
HUF_cds
fig_c_HUF2.jpg
HUF_avg
fig_c_HUF3.jpg
HUF_zscore180
fig_c_HUF4.jpg
HUF_zscore
fig_c_HUF5.jpg
PLN_cds
fig_c_PLN1.jpg
PLN_cds
fig_c_PLN2.jpg
PLN_avg
fig_c_PLN3.jpg
PLN_zscore180
fig_c_PLN4.jpg
PLN_zscore
fig_c_PLN5.jpg
RUB_cds
fig_c_RUB1.jpg
RUB_cds
fig_c_RUB2.jpg
RUB_avg
fig_c_RUB3.jpg
RUB_zscore180
fig_c_RUB4.jpg
RUB_zscore
fig_c_RUB5.jpg
ILS_cds
fig_c_ILS1.jpg
ILS_cds
fig_c_ILS2.jpg
ILS_avg
fig_c_ILS3.jpg
ILS_zscore180
fig_c_ILS4.jpg
ILS_zscore
fig_c_ILS5.jpg
ZAR_cds
fig_c_ZAR1.jpg
ZAR_cds
fig_c_ZAR2.jpg
ZAR_avg
fig_c_ZAR3.jpg
ZAR_zscore180
fig_c_ZAR4.jpg
ZAR_zscore
fig_c_ZAR5.jpg
TRY_cds
fig_c_TRY1.jpg
TRY_cds
fig_c_TRY2.jpg
TRY_avg
fig_c_TRY3.jpg
TRY_zscore180
fig_c_TRY4.jpg
TRY_zscore
fig_c_TRY5.jpg
IDR_cds
fig_c_IDR1.jpg
IDR_cds
fig_c_IDR2.jpg
IDR_avg
fig_c_IDR3.jpg
IDR_zscore180
fig_c_IDR4.jpg
IDR_zscore
fig_c_IDR5.jpg
THB_cds
fig_c_THB1.jpg
THB_cds
fig_c_THB2.jpg
THB_avg
fig_c_THB3.jpg
THB_zscore180
fig_c_THB4.jpg
THB_zscore
fig_c_THB5.jpg
MYR_cds
fig_c_MYR1.jpg
MYR_cds
fig_c_MYR2.jpg
MYR_avg
fig_c_MYR3.jpg
MYR_zscore180
fig_c_MYR4.jpg
MYR_zscore
fig_c_MYR5.jpg
KRW_cds
fig_c_KRW1.jpg
KRW_cds
fig_c_KRW2.jpg
KRW_avg
fig_c_KRW3.jpg
KRW_zscore180
fig_c_KRW4.jpg
KRW_zscore
fig_c_KRW5.jpg
PHP_cds
fig_c_PHP1.jpg
PHP_cds
fig_c_PHP2.jpg
PHP_avg
fig_c_PHP3.jpg
PHP_zscore180
fig_c_PHP4.jpg
PHP_zscore
fig_c_PHP5.jpg
Complete!!!

In [23]:
#df1.tail(10)
#fitlered paramerteres

tail_factor = 500

parameter1 =15
parameter2 =10
parameter3=12
parameter4=12
parameter5=22
print("Complete!!!")

Complete!!!

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [24]:
#fitler
###filteresd last 2 years graph
###with tail  
###proces create summary comparison tables for the techncial creprot
os.chdir('K:/2020_2431/q/cds_report/images/tc/report_c')
print(os.getcwd())

#file location
location_first= ("K:\\2020_2431\\q\\cds_report\\images\\tc\\")
today = str(date.today())+"_"
location_last = '_fig.pdf'

#title_graph="EM CDS - Rating Fit Model "
x_label=" EM CDS "
dateTimeObj = str(datetime.now())
print(dateTimeObj)
title0="EMCDS // Sov CDS "
y_label="Sov CDS 5y"

#country=
lst = ['BRL','COP','MXN','CLP','PEN','CZK','HUF','PLN','RUB','ILS','ZAR','TRY','IDR','THB','MYR','KRW','PHP']
fig_name="fig_d_"
number=0


#number=number+1
#number_t=str(int(number))
#fig_name_t=fig_name+country+number_t+".jpg"
#print(fig_name_t)
#plt.savefig(str(fig_name_t), bbox_inches='tight')


for x in range(len(lst)): 

    country=str(lst[x])  
    
    #cds
    name=country
    cds_series=country+"_cds"
    title=y_label+" "+country
    location=location_first+today+cds_series+location_last
    print(cds_series)
    g=df.filter(regex=str(cds_series))
    g=pd.concat([df[['Date']],g], axis = 1)
    g1 = g.set_index('Date') # setting "Years" as index
    g1=g1.tail(tail_factor)
    g1.head()
    #plot
    fig,ax = plt.subplots(figsize=(parameter1,parameter2))
    g1.plot(kind='line',ax=ax,color=['blue'])
    plt.ylabel(str(y_label), size=parameter3)
    plt.xlabel(str(x_label), size=parameter3)
    plt.tick_params(labelsize=parameter4)
    plt.title(str(title), size=parameter5)
    
    plt.grid(axis='both', alpha=.3)
    last_value_series = g1[str(cds_series)].iloc[-1]
    plt.axhline(last_value_series, color='black', lw=1,linestyle = 'dashed', alpha=0.6)
    first_value_series= g1[str(cds_series)].iloc[0]
    plt.axhline(first_value_series, color='black', lw=1,linestyle = 'dashed', alpha=0.6)
    plt.savefig(location, bbox_inches='tight')
    number=number+1
    number_t=str(int(number))
    fig_name_t=fig_name+country+number_t+".jpg"
    print(fig_name_t)
    plt.savefig(str(fig_name_t), bbox_inches='tight')


    #cds+avg30
    name=country
    cds_series1=country+"_cds"
    cds_series3=country+"_avg30"
    title=y_label+" "+cds_series3
    location=location_first+today+cds_series3+location_last
    print(cds_series)
    g_01=df.filter(regex=str(cds_series1))
    g_03=df.filter(regex=str(cds_series3))
    g=pd.concat([df[['Date']],g_01,g_03], axis = 1)
    g1 = g.set_index('Date') # setting "Years" as index
    g1=g1.tail(tail_factor)
    g1.head()
    #plot
    fig,ax = plt.subplots(figsize=(parameter1,parameter2))
    g1.plot(kind='line',ax=ax,color=['blue',"orange"])
    plt.ylabel(str(y_label), size=parameter3)
    plt.xlabel(str(x_label), size=parameter3)
    plt.tick_params(labelsize=parameter4)
    plt.title(str(title), size=parameter5)
    plt.grid(axis='both', alpha=.3)
    plt.savefig(location, bbox_inches='tight')
    number=number+1
    number_t=str(int(number))
    fig_name_t=fig_name+country+number_t+".jpg"
    print(fig_name_t)
    plt.savefig(str(fig_name_t), bbox_inches='tight')
    
    
    
    #avgsssss
    name=country
    cds_series=country+"_avg"
    cds_series1=country+"_avg5"
    cds_series2=country+"_avg15"
    cds_series3=country+"_avg30"
    cds_series4=country+"_avg90"
    title=y_label+" "+country
    location=location_first+today+cds_series+location_last
    print(cds_series)
    g_01=df.filter(regex=str(cds_series1))
    g_02=df.filter(regex=str(cds_series2))
    g_03=df.filter(regex=str(cds_series3))
    g_04=df.filter(regex=str(cds_series4))
    g=pd.concat([df[['Date']],g_01,g_02,g_03,g_04], axis = 1)
    g1 = g.set_index('Date') # setting "Years" as index
    g1=g1.tail(tail_factor)
    g1.head()
    #plot
    fig,ax = plt.subplots(figsize=(parameter1,parameter2))
    g1.plot(kind='line',ax=ax,color=['blue',"yellow","orange","red"])
    plt.ylabel(str(y_label), size=parameter3)
    plt.xlabel(str(x_label), size=parameter3)
    plt.tick_params(labelsize=parameter4)
    plt.title(str(title), size=parameter5)
    plt.grid(axis='both', alpha=.3)
    plt.savefig(location, bbox_inches='tight')
    number=number+1
    number_t=str(int(number))
    fig_name_t=fig_name+country+number_t+".jpg"
    print(fig_name_t)
    plt.savefig(str(fig_name_t), bbox_inches='tight')
    
    
    
    #zscore
    name=country
    cds_series=country+"_zscore180"
    cds_series2=country+"_z180"
    title=y_label+" "+cds_series
    location=location_first+today+cds_series+location_last
    print(cds_series)
    g_02=df.filter(regex=str(cds_series2))
    g=pd.concat([df[['Date']],g_02], axis = 1)
    g1 = g.set_index('Date') # setting "Years" as index
    g1=g1.tail(tail_factor)
    g1.head()
    #plot
    fig,ax = plt.subplots(figsize=(parameter1,parameter2))
    g1.plot(kind='line',ax=ax,color=['blue'])
    plt.ylabel(str(y_label), size=parameter3)
    plt.xlabel(str(x_label), size=parameter3)
    plt.tick_params(labelsize=parameter4)
    plt.title(str(title), size=parameter5)
    plt.grid(axis='both', alpha=.3)
    plt.axhline(0, color='black', lw=1, alpha=0.6)
    plt.savefig(location, bbox_inches='tight')
    number=number+1
    number_t=str(int(number))
    fig_name_t=fig_name+country+number_t+".jpg"
    print(fig_name_t)
    plt.savefig(str(fig_name_t), bbox_inches='tight')
    

    #all zscores
    name=country
    cds_series=country+"_zscore"
    cds_series1=country+"_z90"
    cds_series2=country+"_z180"
    cds_series3=country+"_z360"
    title=y_label+" "+cds_series
    location=location_first+today+cds_series+location_last
    print(cds_series)
    g_01=df.filter(regex=str(cds_series1))
    g_02=df.filter(regex=str(cds_series2))
    g_03=df.filter(regex=str(cds_series3))
    g=pd.concat([df[['Date']],g_01,g_02,g_03], axis = 1)
    g1 = g.set_index('Date') # setting "Years" as index
    g1=g1.tail(tail_factor)
    g1.head()
    #plot
    fig,ax = plt.subplots(figsize=(parameter1,parameter2))
    g1.plot(kind='line',ax=ax,color=['blue',"gray",'black'])
    plt.ylabel(str(y_label), size=parameter3)
    plt.xlabel(str(x_label), size=parameter3)
    plt.tick_params(labelsize=parameter4)
    plt.title(str(title), size=parameter5)
    plt.grid(axis='both', alpha=.3)
    plt.axhline(0, color='black', lw=1, alpha=0.6)
    plt.savefig(location, bbox_inches='tight')
    number=number+1
    number_t=str(int(number))
    fig_name_t=fig_name+country+number_t+".jpg"
    print(fig_name_t)
    plt.savefig(str(fig_name_t), bbox_inches='tight')
    number=0

    del g1
    del location
    del g_01
    del g_02
    del g_03
    del cds_series
    del cds_series1
    del cds_series2
    del cds_series3
    del cds_series4
    
    
#reset number    
number=0
print("Complete!!!")

K:\2020_2431\q\cds_report\images\tc\report_c
2021-10-14 12:31:07.735962
BRL_cds
fig_d_BRL1.jpg
BRL_cds
fig_d_BRL2.jpg
BRL_avg
fig_d_BRL3.jpg
BRL_zscore180
fig_d_BRL4.jpg
BRL_zscore
fig_d_BRL5.jpg
COP_cds
fig_d_COP1.jpg
COP_cds
fig_d_COP2.jpg
COP_avg
fig_d_COP3.jpg
COP_zscore180
fig_d_COP4.jpg
COP_zscore
fig_d_COP5.jpg
MXN_cds
fig_d_MXN1.jpg
MXN_cds
fig_d_MXN2.jpg
MXN_avg
fig_d_MXN3.jpg
MXN_zscore180
fig_d_MXN4.jpg
MXN_zscore
fig_d_MXN5.jpg
CLP_cds
fig_d_CLP1.jpg
CLP_cds
fig_d_CLP2.jpg
CLP_avg
fig_d_CLP3.jpg
CLP_zscore180
fig_d_CLP4.jpg
CLP_zscore
fig_d_CLP5.jpg
PEN_cds
fig_d_PEN1.jpg
PEN_cds
fig_d_PEN2.jpg
PEN_avg
fig_d_PEN3.jpg
PEN_zscore180
fig_d_PEN4.jpg
PEN_zscore
fig_d_PEN5.jpg
CZK_cds
fig_d_CZK1.jpg
CZK_cds
fig_d_CZK2.jpg
CZK_avg
fig_d_CZK3.jpg
CZK_zscore180
fig_d_CZK4.jpg
CZK_zscore
fig_d_CZK5.jpg
HUF_cds
fig_d_HUF1.jpg
HUF_cds
fig_d_HUF2.jpg
HUF_avg
fig_d_HUF3.jpg
HUF_zscore180
fig_d_HUF4.jpg
HUF_zscore
fig_d_HUF5.jpg
PLN_cds
fig_d_PLN1.jpg
PLN_cds
fig_d_PLN2.jpg
PLN_avg
fig_d_PLN3.jpg
PLN_zscore180
fig_d_PLN4.jpg
PLN_zscore
fig_d_PLN5.jpg
RUB_cds
fig_d_RUB1.jpg
RUB_cds
fig_d_RUB2.jpg
RUB_avg
fig_d_RUB3.jpg
RUB_zscore180
fig_d_RUB4.jpg
RUB_zscore
fig_d_RUB5.jpg
ILS_cds
fig_d_ILS1.jpg
ILS_cds
fig_d_ILS2.jpg
ILS_avg
fig_d_ILS3.jpg
ILS_zscore180
fig_d_ILS4.jpg
ILS_zscore
fig_d_ILS5.jpg
ZAR_cds
fig_d_ZAR1.jpg
ZAR_cds
fig_d_ZAR2.jpg
ZAR_avg
fig_d_ZAR3.jpg
ZAR_zscore180
fig_d_ZAR4.jpg
ZAR_zscore
fig_d_ZAR5.jpg
TRY_cds
fig_d_TRY1.jpg
TRY_cds
fig_d_TRY2.jpg
TRY_avg
fig_d_TRY3.jpg
TRY_zscore180
fig_d_TRY4.jpg
TRY_zscore
fig_d_TRY5.jpg
IDR_cds
fig_d_IDR1.jpg
IDR_cds
fig_d_IDR2.jpg
IDR_avg
fig_d_IDR3.jpg
IDR_zscore180
fig_d_IDR4.jpg
IDR_zscore
fig_d_IDR5.jpg
THB_cds
fig_d_THB1.jpg
THB_cds
fig_d_THB2.jpg
THB_avg
fig_d_THB3.jpg
THB_zscore180
fig_d_THB4.jpg
THB_zscore
fig_d_THB5.jpg
MYR_cds
fig_d_MYR1.jpg
MYR_cds
fig_d_MYR2.jpg
MYR_avg
fig_d_MYR3.jpg
MYR_zscore180
fig_d_MYR4.jpg
MYR_zscore
fig_d_MYR5.jpg
KRW_cds
fig_d_KRW1.jpg
KRW_cds
fig_d_KRW2.jpg
KRW_avg
fig_d_KRW3.jpg
KRW_zscore180
fig_d_KRW4.jpg
KRW_zscore
fig_d_KRW5.jpg
PHP_cds
fig_d_PHP1.jpg
PHP_cds
fig_d_PHP2.jpg
PHP_avg
fig_d_PHP3.jpg
PHP_zscore180
fig_d_PHP4.jpg
PHP_zscore
fig_d_PHP5.jpg
Complete!!!

In [25]:
###https://stackoverflow.com/questions/30227466/combine-several-images-horizontally-with-python
#part 3 pdf ALL COUNTRUES
os.chdir('K:/2020_2431/q/cds_report/images/tc/report_c')
print(os.getcwd())


final_location_first = ("K:\\2020_2431\\q\\cds_report\\images\\tc\\report_f\\006_")
final_location_last = '.pdf'

lst = ['BRL','COP','MXN','CLP','PEN','CZK','HUF','PLN','RUB','ILS','ZAR','TRY','IDR','THB','MYR','KRW','PHP']
#list_im = ["fig_c_BRL4.jpg","fig_c_BRL5.jpg"]

for x in range(len(lst)):      
    country=str(lst[x])  
    print(country)
    #cds
    name=country

    #######
    list_im = [str("fig_c_"+country+"1.jpg"),str("fig_c_"+country+"2.jpg"),str("fig_c_"+country+"3.jpg")]
    imgs    = [ PIL.Image.open(i) for i in list_im ]
    # pick the image which is the smallest, and resize the others to match it (can be arbitrary image shape here)
    min_shape = sorted( [(np.sum(i.size), i.size ) for i in imgs])[0][1]
    imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

    # save that beautiful picture
    imgs_comb = np.vstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )
    imgs_comb = PIL.Image.fromarray( imgs_comb)
    imgs_comb.save( str("fig_c_"+country+"_1.jpg") )    


    #######
    list_im = [str("fig_c_"+country+"4.jpg"),str("fig_c_"+country+"5.jpg")]
    imgs    = [ PIL.Image.open(i) for i in list_im ]
    # pick the image which is the smallest, and resize the others to match it (can be arbitrary image shape here)
    min_shape = sorted( [(np.sum(i.size), i.size ) for i in imgs])[0][1]
    imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

    # save that beautiful picture
    imgs_comb = np.vstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )
    imgs_comb = PIL.Image.fromarray( imgs_comb)
    imgs_comb.save( str("fig_c_"+country+"_2.jpg") )   

    ######

    list_im = [str("fig_c_"+country+"_1.jpg"),str("fig_c_"+country+"_2.jpg")]
    imgs    = [ PIL.Image.open(i) for i in list_im ]
    # pick the image which is the smallest, and resize the others to match it (can be arbitrary image shape here)
    min_shape = sorted( [(np.sum(i.size), i.size ) for i in imgs])[0][1]
    imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

    # save that beautiful picture
    imgs_comb = PIL.Image.fromarray( imgs_comb)
    imgs_comb.save( str("fig_c_"+country+".pdf") ) 
    imgs_comb.save( str(final_location_first+country+final_location_last) ) 

    
    
print("Complete!!!")

K:\2020_2431\q\cds_report\images\tc\report_c
BRL

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
<ipython-input-25-324063ebd0da>:24: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

COP
MXN
CLP
PEN
CZK
HUF
PLN
RUB
ILS
ZAR
TRY
IDR
THB
MYR
KRW
PHP
Complete!!!

In [26]:
#new version!!!!
###https://stackoverflow.com/questions/30227466/combine-several-images-horizontally-with-python
#part 3 pdf ALL COUNTRUES
os.chdir('K:/2020_2431/q/cds_report/images/tc/report_c')
print(os.getcwd())


final_location_first = ("K:\\2020_2431\\q\\cds_report\\images\\tc\\report_f\\006_")
final_location_last = '.pdf'

lst = ['BRL','COP','MXN','CLP','PEN','CZK','HUF','PLN','RUB','ILS','ZAR','TRY','IDR','THB','MYR','KRW','PHP']
#list_im = ["fig_c_BRL4.jpg","fig_c_BRL5.jpg"]

#fig_d_BRL1
#fig_c_BRL3
#fig_d_BRL4
#fig_c_BRL5

for x in range(len(lst)):      
    country=str(lst[x])  
    
    #cds
    name=country
    print(name)

    #######
    list_im = [str("fig_d_"+country+"1.jpg"),str("fig_c_"+country+"3.jpg"),]
    imgs    = [ PIL.Image.open(i) for i in list_im ]
    # pick the image which is the smallest, and resize the others to match it (can be arbitrary image shape here)
    min_shape = sorted( [(np.sum(i.size), i.size ) for i in imgs])[0][1]
    imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

    # save that beautiful picture
    imgs_comb = np.vstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )
    imgs_comb = PIL.Image.fromarray( imgs_comb)
    imgs_comb.save( str("fig_d_"+country+"_1.jpg") )    


    #######
    list_im = [str("fig_d_"+country+"4.jpg"),str("fig_c_"+country+"5.jpg")]
    imgs    = [ PIL.Image.open(i) for i in list_im ]
    # pick the image which is the smallest, and resize the others to match it (can be arbitrary image shape here)
    min_shape = sorted( [(np.sum(i.size), i.size ) for i in imgs])[0][1]
    imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

    # save that beautiful picture
    imgs_comb = np.vstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )
    imgs_comb = PIL.Image.fromarray( imgs_comb)
    imgs_comb.save( str("fig_d_"+country+"_2.jpg") )   

    ######

    list_im = [str("fig_d_"+country+"_1.jpg"),str("fig_d_"+country+"_2.jpg")]
    imgs    = [ PIL.Image.open(i) for i in list_im ]
    # pick the image which is the smallest, and resize the others to match it (can be arbitrary image shape here)
    min_shape = sorted( [(np.sum(i.size), i.size ) for i in imgs])[0][1]
    imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

    # save that beautiful picture
    imgs_comb = PIL.Image.fromarray( imgs_comb)
    imgs_comb.save( str("fig_d_"+country+".pdf") ) 
    imgs_comb.save( str(final_location_first+country+final_location_last) ) 
    
print("Complete!!!")

K:\2020_2431\q\cds_report\images\tc\report_c
BRL

<ipython-input-26-c707bcb15ffd>:31: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

COP
MXN
CLP
PEN
CZK
HUF
PLN
RUB
ILS
ZAR
TRY
IDR
THB
MYR
KRW
PHP
Complete!!!

In [27]:
#####cross correlations last 90
###### cross corelaiton last 180

###https://heartbeat.fritz.ai/seaborn-heatmaps-13-ways-to-customize-correlation-matrix-visualizations-f1c49c816f07
#part 3 pdf ALL COUNTRUES
os.chdir('K:/2020_2431/q/cds_report/images/tc/report_c')
print(os.getcwd())

final_location_first = ("K:\\2020_2431\\q\\cds_report\\images\\tc\\report_f\\007_")
final_location_last = '.pdf'

matrix_cc = df[['Date','BRL_cds','COP_cds','MXN_cds','CLP_cds','PEN_cds','CZK_cds',
       'HUF_cds','PLN_cds','RUB_cds','ILS_cds','ZAR_cds','TRY_cds','IDR_cds',
       'THB_cds','MYR_cds','KRW_cds','PHP_cds']]

matrix_cc=matrix_cc.set_index('Date')
matrix_cc1=matrix_cc.tail(180)
matrix_cc2=matrix_cc.tail(90)

today_c = str(date.today())



#print(matrix_cc1)
#print(matrix_cc2)

import seaborn as sns



fig,ax = plt.subplots(figsize=(20,10))
sns.heatmap(matrix_cc1.corr(), annot = True, vmin=-1, vmax=1, center= 0, cmap= 'coolwarm')
plt.title(str("Cross Correlation Matrix _ Last 180d "+today_c), size=17)
plt.savefig("007_CC_180D.jpg", bbox_inches='tight')


fig,ax = plt.subplots(figsize=(20,10))
sns.heatmap(matrix_cc2.corr(), annot = True, vmin=-1, vmax=1, center= 0, cmap= 'coolwarm')
plt.title(str("Cross Correlation Matrix _ Last 90d "+today_c), size=17)
plt.savefig("007_CC_90D.jpg", bbox_inches='tight')

#######
list_im = [str("007_CC_90D.jpg"),str("007_CC_180D.jpg"),]
imgs    = [ PIL.Image.open(i) for i in list_im ]
 # pick the image which is the smallest, and resize the others to match it (can be arbitrary image shape here)
min_shape = sorted( [(np.sum(i.size), i.size ) for i in imgs])[0][1]
imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

# save that beautiful picture
imgs_comb = np.vstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )
imgs_comb = PIL.Image.fromarray( imgs_comb)
imgs_comb.save( str("fig_cross_correlation_1.jpg") )    
imgs_comb.save( str(final_location_first+"correlation"+final_location_last) ) 



  

    

print("Complete!!!")

K:\2020_2431\q\cds_report\images\tc\report_c

<ipython-input-27-54b7786444e9>:47: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  imgs_comb = np.hstack( (np.asarray( i.resize(min_shape) ) for i in imgs ) )

Complete!!!

In [28]:
##############Aggregated output
os.chdir('K:/2020_2431/q/cds_report/output')

output001 = pd.read_csv ('output001.csv')
output002 = pd.read_csv ('output002.csv')
output003 = pd.read_csv ('output003.csv')
output004 = pd.read_csv ('output004.csv')

#print(output001)
#print(output002)
#print(output003)
#print(output004)


output001['country']=output001['country'].str.lower()
output002['country']=output002['country'].str.lower()
output003['country']=output003['country'].str.lower()
output004['country']=output004['country'].str.lower()

output002=output002[['country','model002_m0100']]
output003=output003[['country','model003_m0100','model003_m0200','model003_m0300','model003_m0400','model003_m0500']]
output004=output004[['country','model004_m0100','model004_m0200','model004_m0300']]

output=pd.merge(output001, output002,  how='left', left_on=['country'], right_on = ['country'])
output=pd.merge(output, output003,  how='left', left_on=['country'], right_on = ['country'])
output=pd.merge(output, output004,  how='left', left_on=['country'], right_on = ['country'])
output.rename(columns={'cds_latest':'cds'}, inplace=True)
output=output.reset_index(drop=True)


##filter
output = output[output.country != 'india']
#print(output)
print("Coimpelte")

Coimpelte

In [29]:

########---------------------
final_location_first = ("K:\\2020_2431\\q\\cds_report\\images\\tc\\report_f\\005_")
final_location_last = '.pdf'
name="Complete_Summary"
location= str(final_location_first+name+final_location_last) 


#print(df1)
end=str(date.today())
variable_text='latest CDS market value'
title=str("EM-CDS Quantitative Framework "+end)
y_label="Sov 5Y CDS"
x_label="EM Country -model001 Rating, model002_m0100 Governance, model003 Economic, model004 Decision Tree"
z_title="EM-CDS Quantitative Framework"


parameter_y=15
parameter_x=15
parameter_z=15
parameter_f1=15    
parameter_f2=8   
parameter_t=10


#name_text=name + name_series
#z_title1=z_title+name_text
#location=location_first+name_series+location_last

graph_input=output
chart=graph_input
order_t=chart[['country','cds']]
order_t = order_t.sort_values(['cds'], ascending=[False])
order_t = order_t.reset_index()
order_t = order_t.rename(columns={"index":"order"})
order_t['order_1'] = (order_t.index + 1)*10
del order_t['cds']
print(order_t)
o_list=chart.columns 
o_list = pd.DataFrame(o_list)
o_list.columns=["order_sort"]
o_list.drop(o_list.index[:1], inplace=True)
o_list = o_list.reset_index()
o_list = o_list.rename(columns={"index":"order"})
o_list['order_2'] = (o_list.index + 1)
print(o_list)
 

chart.set_index('country', inplace=True)
df1 = chart.stack().reset_index().set_index('country').rename(columns={'level_1': 'Status', 0: 'Values'})
df1 = df1.reset_index()
df1=pd.merge(df1, order_t[['country','order_1']],  how='left', left_on=['country'], right_on = ['country']) 
df1=pd.merge(df1, o_list[['order_sort','order_2']],  how='left', left_on=['Status'], right_on = ['order_sort']) 
df1['order_3']=(df1['order_1']*df1['order_2'])

df1 = df1.sort_values(['order_3'], ascending=[True])
del df1['order_1']
del df1['order_2']
#be careful
df1['Values']=(df1['Values']*1)
print(df1)

#graph specifics
#large and height
plt.figure(figsize=(parameter_f1,parameter_f2))
sns.set_style('whitegrid')
splot=sns.barplot(x='country', hue="Status", y="Values",
                      palette=["navy",
                               "darkorange","darkorange","darkorange","darkorange",
                               "lightsalmon","lightsalmon","lightsalmon","lightsalmon","lightsalmon",
                               "orange",
                               "moccasin","moccasin","moccasin","moccasin"], data=df1)
plt.ylabel(y_label, size=parameter_y)
plt.xlabel(x_label, size=parameter_x)
plt.title(z_title, size=parameter_z)
plt.tick_params(labelsize=parameter_t)


#plt.savefig("grouped_barplot_Seaborn_barplot_Python.png")
plt.savefig(location)
plt.show()

print("COmplete")

    order         country  order_1
0       5          turkey       10
1       7    south africa       20
2       0          brazil       30
3       1        colombia       40
4       6          russia       50
5       2          mexico       60
6       4            peru       70
7      14       indonesia       80
8       9         hungary       90
9       3           chile      100
10      8          poland      110
11     17     philippines      120
12     10          israel      130
13     15        malaysia      140
14     18        thailand      150
15     13           china      160
16     11  czech republic      170
17     12           korea      180
    order      order_sort  order_2
0       1             cds        1
1       2  model001_m0110        2
2       3  model001_m0120        3
3       4  model001_m0130        4
4       5  model001_m0200        5
5       6  model002_m0100        6
6       7  model003_m0100        7
7       8  model003_m0200        8
8       9  model003_m0300        9
9      10  model003_m0400       10
10     11  model003_m0500       11
11     12  model004_m0100       12
12     13  model004_m0200       13
13     14  model004_m0300       14
          country          Status  Values      order_sort  order_3
70         turkey             cds  410.89             cds       10
71         turkey  model001_m0110  265.20  model001_m0110       20
94   south africa             cds  207.88             cds       20
0          brazil             cds  185.15             cds       30
72         turkey  model001_m0120  268.30  model001_m0120       30
..            ...             ...     ...             ...      ...
210      malaysia  model004_m0300   69.00  model004_m0300     1960
168         korea  model003_m0500   21.30  model003_m0500     1980
181         china  model004_m0200   64.00  model004_m0200     2080
238      thailand  model004_m0300   69.00  model004_m0300     2100
182         china  model004_m0300   69.00  model004_m0300     2240

[239 rows x 5 columns]
COmplete

<ipython-input-29-51f270447228>:80: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

In [30]:
print(output)
print(output.columns)
output.reset_index(level=0, inplace=True)
output.rename(columns={"model001_m0110":'001_Rating_m0110'}, inplace=True)
output.rename(columns={"model001_m0120":'001_Rating_m0120'}, inplace=True)
output.rename(columns={"model001_m0130":'001_Rating_m0130'}, inplace=True)
output.rename(columns={"model001_m0200":'001_Rating_m0200'}, inplace=True)
output.rename(columns={"model002_m0100":'002_Institutional_WBI_m0100'}, inplace=True)
output.rename(columns={"model003_m0100":'003_CrossEconomic_m0100'}, inplace=True)
output.rename(columns={"model003_m0200":'003_CrossEconomic_m0200'}, inplace=True)
output.rename(columns={"model003_m0300":'003_CrossEconomic_m0300'}, inplace=True)
output.rename(columns={"model003_m0400":'003_CrossEconomic_m0400'}, inplace=True)
output.rename(columns={"model003_m0500":'003_CrossEconomic_m0500'}, inplace=True)
output.rename(columns={"model004_m0100":'004_DecTree_Economic_m0100'}, inplace=True)
output.rename(columns={"model004_m0200":'004_DecTree_Economic_m0200'}, inplace=True)
output.rename(columns={"model004_m0300":'004_DecTree_Economic_m0300'}, inplace=True)
print(output.columns)

                   cds  model001_m0110  model001_m0120  model001_m0130  \
country
brazil          185.15           191.5           194.8           198.8
colombia        134.87            95.5           102.4           110.7
mexico           97.11            73.6            78.8            85.1
chile            60.42            38.7            38.9            39.0
peru             92.77            53.4            56.6            60.3
turkey          410.89           265.2           268.3           269.6
russia           97.12            87.5            86.1            85.1
south africa    207.88           191.5           203.1           214.9
poland           51.47            43.5            42.6            41.6
hungary          62.60            80.1            75.6            71.4
israel           47.60            32.1            31.3            30.6
czech republic   38.50            29.6            28.9            28.4
korea            19.95            27.2            26.7            26.4
china            39.13            33.5            32.7            31.9
indonesia        78.42            73.6            75.6            77.8
malaysia         47.45            49.6            50.5            51.4
philippines      48.16            67.7            66.6            65.6
thailand         42.14            57.6            56.6            55.6

                model001_m0200  model002_m0100  model003_m0100  \
country
brazil                   180.4            97.2           149.7
colombia                 114.4            91.7           134.2
mexico                    95.3           108.2           120.9
chile                     48.7            43.7            67.7
peru                      73.5            99.7            97.5
turkey                   237.5             NaN           438.7
russia                   101.5           108.4           122.2
south africa             186.4            83.0           215.2
poland                    55.1            65.6            45.1
hungary                   92.5            78.1            80.3
israel                    31.5            41.3            32.6
czech republic            24.4            57.5            70.8
korea                     17.8            45.4            23.1
china                     35.1            91.6            25.4
indonesia                 92.4            96.0            71.7
malaysia                  66.3            64.8            49.0
philippines               84.1            99.6           108.6
thailand                  73.6            88.0            49.9

                model003_m0200  model003_m0300  model003_m0400  \
country
brazil                   139.7           165.4           177.3
colombia                 148.7           145.5           117.4
mexico                   113.4           112.5           102.3
chile                     71.6            65.3            60.1
peru                      90.9            97.0            78.2
turkey                   438.7           438.7           438.7
russia                   114.5            91.5           110.9
south africa             215.2           215.2           215.2
poland                    55.5            78.6            72.0
hungary                   90.9           103.7           113.3
israel                    23.4            21.7            36.9
czech republic            45.9            33.9            32.9
korea                     32.3            14.2            14.2
china                      5.9            30.4            32.2
indonesia                 95.3            88.2            80.5
malaysia                  87.3            73.2            67.9
philippines               65.1            56.7            82.0
thailand                  68.3            70.9            70.4

                model003_m0500  model004_m0100  model004_m0200  model004_m0300
country
brazil                   160.4           206.0           201.0           217.0
colombia                 140.5           135.0           173.0           145.0
mexico                   100.3           120.0            90.0            69.0
chile                     72.8            71.0            90.0            69.0
peru                      77.4            71.0            90.0            69.0
turkey                   438.7           448.0           469.0           411.0
russia                   107.6             NaN             NaN             NaN
south africa             215.2           176.0           206.0           210.0
poland                    59.8            56.0            64.0            69.0
hungary                  102.3            50.0            65.0           103.0
israel                    30.0             NaN             NaN             NaN
czech republic            34.7             NaN             NaN             NaN
korea                     21.3             NaN             NaN             NaN
china                      8.1            56.0            64.0            69.0
indonesia                 95.9            56.0            64.0            69.0
malaysia                  85.5            56.0            64.0            69.0
philippines               78.2            56.0            64.0            69.0
thailand                  73.9            56.0            64.0            69.0
Index(['cds', 'model001_m0110', 'model001_m0120', 'model001_m0130',
       'model001_m0200', 'model002_m0100', 'model003_m0100', 'model003_m0200',
       'model003_m0300', 'model003_m0400', 'model003_m0500', 'model004_m0100',
       'model004_m0200', 'model004_m0300'],
      dtype='object')
Index(['country', 'cds', '001_Rating_m0110', '001_Rating_m0120',
       '001_Rating_m0130', '001_Rating_m0200', '002_Institutional_WBI_m0100',
       '003_CrossEconomic_m0100', '003_CrossEconomic_m0200',
       '003_CrossEconomic_m0300', '003_CrossEconomic_m0400',
       '003_CrossEconomic_m0500', '004_DecTree_Economic_m0100',
       '004_DecTree_Economic_m0200', '004_DecTree_Economic_m0300'],
      dtype='object')

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [31]:
########---------------------
final_location_first = ("K:\\2020_2431\\q\\cds_report\\images\\tc\\report_f\\005_")
final_location_last = '_2.pdf'
name="Complete_Summary"
location= str(final_location_first+name+final_location_last) 


#print(df1)
end=str(date.today())
variable_text='latest CDS market value'
title=str("EM-CDS Quantitative Framework "+end)
y_label="Sov 5Y CDS"
x_label="EM Country -model001 Rating, model002_m0100 Governance, model003 Economic, model004 Decision Tree"
z_title="EM-CDS Quantitative Framework"


parameter_y=15
parameter_x=15
parameter_z=15
parameter_f1=16   
parameter_f2=9  
parameter_t=10


#name_text=name + name_series
#z_title1=z_title+name_text
#location=location_first+name_series+location_last

graph_input=output
chart=graph_input
order_t=chart[['country','cds']]
order_t = order_t.sort_values(['cds'], ascending=[False])
order_t = order_t.reset_index()
order_t = order_t.rename(columns={"index":"order"})
order_t['order_1'] = (order_t.index + 1)*10
del order_t['cds']
print(order_t)
o_list=chart.columns 
o_list = pd.DataFrame(o_list)
o_list.columns=["order_sort"]
o_list.drop(o_list.index[:1], inplace=True)
o_list = o_list.reset_index()
o_list = o_list.rename(columns={"index":"order"})
o_list['order_2'] = (o_list.index + 1)
print(o_list)
 

chart.set_index('country', inplace=True)
df1 = chart.stack().reset_index().set_index('country').rename(columns={'level_1': 'Status', 0: 'Values'})
df1 = df1.reset_index()
df1=pd.merge(df1, order_t[['country','order_1']],  how='left', left_on=['country'], right_on = ['country']) 
df1=pd.merge(df1, o_list[['order_sort','order_2']],  how='left', left_on=['Status'], right_on = ['order_sort']) 
df1['order_3']=(df1['order_1']*df1['order_2'])

df1 = df1.sort_values(['order_3'], ascending=[True])
del df1['order_1']
del df1['order_2']
#be careful
df1['Values']=(df1['Values']*1)
print(df1)

#graph specifics
#large and height
plt.figure(figsize=(parameter_f1,parameter_f2))
sns.set_style('whitegrid')
splot=sns.barplot(x='country', hue="Status", y="Values",
                      palette=["blue",
                               "orange","orange","orange","orange",
                               "moccasin","moccasin","moccasin","moccasin","moccasin",
                               "lightsteelblue",
                               "lightcoral","lightcoral","lightcoral","lightcoral"], data=df1)
plt.ylabel(y_label, size=parameter_y)
plt.xlabel(x_label, size=parameter_x)
plt.title(z_title, size=parameter_z)
plt.tick_params(labelsize=parameter_t)


#plt.savefig("grouped_barplot_Seaborn_barplot_Python.png")
plt.savefig(location)
plt.show()

#darkorange
#lightsalmon
#lightcoral
#mistyrose

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    order         country  order_1
0       5          turkey       10
1       7    south africa       20
2       0          brazil       30
3       1        colombia       40
4       6          russia       50
5       2          mexico       60
6       4            peru       70
7      14       indonesia       80
8       9         hungary       90
9       3           chile      100
10      8          poland      110
11     16     philippines      120
12     10          israel      130
13     15        malaysia      140
14     17        thailand      150
15     13           china      160
16     11  czech republic      170
17     12           korea      180
    order                   order_sort  order_2
0       1                          cds        1
1       2             001_Rating_m0110        2
2       3             001_Rating_m0120        3
3       4             001_Rating_m0130        4
4       5             001_Rating_m0200        5
5       6  002_Institutional_WBI_m0100        6
6       7      003_CrossEconomic_m0100        7
7       8      003_CrossEconomic_m0200        8
8       9      003_CrossEconomic_m0300        9
9      10      003_CrossEconomic_m0400       10
10     11      003_CrossEconomic_m0500       11
11     12   004_DecTree_Economic_m0100       12
12     13   004_DecTree_Economic_m0200       13
13     14   004_DecTree_Economic_m0300       14
          country                      Status  Values  \
70         turkey                         cds  410.89
71         turkey            001_Rating_m0110  265.20
94   south africa                         cds  207.88
0          brazil                         cds  185.15
72         turkey            001_Rating_m0120  268.30
..            ...                         ...     ...
210      malaysia  004_DecTree_Economic_m0300   69.00
168         korea     003_CrossEconomic_m0500   21.30
181         china  004_DecTree_Economic_m0200   64.00
238      thailand  004_DecTree_Economic_m0300   69.00
182         china  004_DecTree_Economic_m0300   69.00

                     order_sort  order_3
70                          cds       10
71             001_Rating_m0110       20
94                          cds       20
0                           cds       30
72             001_Rating_m0120       30
..                          ...      ...
210  004_DecTree_Economic_m0300     1960
168     003_CrossEconomic_m0500     1980
181  004_DecTree_Economic_m0200     2080
238  004_DecTree_Economic_m0300     2100
182  004_DecTree_Economic_m0300     2240

[239 rows x 5 columns]

<ipython-input-31-be0ec51b0417>:80: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

In [32]:
#import os
from PyPDF2 import PdfFileMerger

source_dir = 'K:/2020_2431/q/cds_report/images/tc/report_f/'
source_dir2 = 'K:/2020_2431/q/cds_report/images/tc/report_f2/'
merger = PdfFileMerger()

for item in os.listdir(source_dir):
    if item.endswith('pdf'):
        #print(item)
        merger.append(source_dir + item)

merger.write(source_dir2 + 'EMCDS_0001_Technical_Complete.pdf')       
merger.close()
print("Complete!!!")

C:\Anaconda_2020.11\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Complete!!!

In [33]:
###review
####cds_tmp = pd.read_csv (r'K:\2020_2431\q\sandbox\cds_tmp.csv')
#source_dir2 = 'K:/2020_2431/q/cds_report/images/tc/report_f2/'

In [34]:
timeclock.stop()
#Elapsed time: 207.3372 seconds
#207.3371597

Elapsed time: 213.3023 seconds

213.3023321